const G = {A1:[],A2:[],B1:[],B2:[],C1:[]};
const r=(lv,t,tag,txt,ex,warn)=>G[lv].push({t,tag,txt,ex,warn});

r("A1","Читання й вимова","Фонетика","Німецька читається за правилами — вивчивши їх раз, ти прочитаєш будь-яке слово. Ключове: <b>ei</b> = «ай», <b>ie</b> = «і», <b>eu/äu</b> = «ой», <b>sch</b> = «ш», <b>st-/sp-</b> на початку = «шт-/шп-», <b>v</b> = «ф», <b>w</b> = «в», <b>z</b> = «ц», <b>ch</b> після a,o,u = «х», після e,i = м'яке «хь».",[["Ich heiße Eva und spiele Klavier.","Іх ХАЙсе Ева унт ШПІле Клавір."],["Straße, Schule, sieben, teuer","штрасе, шуле, зібен, тойер"]],"Наголос майже завжди на першому складі кореня. У префіксах be-, ge-, ver-, ent- наголос на них НЕ падає: verSTEhen.");
r("A1","Три роди й артикль","Іменник","Кожен іменник має рід: <span class='k-der'>der</span> (чол.), <span class='k-die'>die</span> (жін.), <span class='k-das'>das</span> (сер.). Рід не збігається з українським і його не можна вгадати з логіки — тому слово вчиться ЛИШЕ разом з артиклем. Усі іменники пишуться з великої літери.",[["das Mädchen","дівчинка — середнього роду, попри стать"],["die Sonne / der Mond","сонце жіноче, місяць чоловічий — навпаки до української"]],"Множина завжди die: die Tische, die Frauen, die Kinder.");
r("A1","Präsens: дієвідміна","Дієслово","Основа + закінчення: ich -e, du -st, er/sie/es -t, wir -en, ihr -t, sie/Sie -en. У дієслів на -a-, -e- в корені 2 і 3 особа однини змінюють голосну: fahren → du fährst, sprechen → du sprichst, lesen → du liest.",[["ich lerne, du lernst, er lernt, wir lernen","я вчу, ти вчиш, він вчить, ми вчимо"],["ich fahre, du fährst, er fährt","я їду, ти їдеш, він їде"]],"sein і haben неправильні: ich bin/du bist/er ist; ich habe/du hast/er hat. Вивчити напам'ять першими.");
r("A1","Дієслово на другому місці","Порядок слів","У розповідному реченні дієслово стоїть СУВОРО на другому місці — незалежно від того, що на першому. Якщо речення починається з обставини, підмет переходить після дієслова.",[["Ich gehe heute ins Kino.","Я йду сьогодні в кіно."],["Heute gehe ich ins Kino.","Сьогодні йду я в кіно."]],"Це найчастіша помилка слов'ян: «Heute ich gehe» — неправильно. Дієслово не зрушується ніколи.");
r("A1","Питання","Порядок слів","W-питання: питальне слово + дієслово + підмет. Так-ні питання: дієслово на першому місці. Питальні слова: wer (хто), was (що), wo (де), wohin (куди), wann (коли), warum (чому), wie (як), wie viel (скільки), welcher (який).",[["Wo wohnst du?","Де ти живеш?"],["Kommst du mit?","Ти йдеш зі мною?"]]);
r("A1","Akkusativ","Відмінок","Знахідний — прямий додаток (кого? що?). Змінюється ТІЛЬКИ чоловічий рід: der → den, ein → einen. Жіночий, середній і множина лишаються як у називному.",[["Ich sehe den Mann.","Я бачу чоловіка."],["Ich kaufe einen Tisch, eine Lampe, ein Buch.","Купую стіл, лампу, книжку."]],"Прийменники завжди з Akkusativ: durch, für, gegen, ohne, um, bis.");
r("A1","Модальні дієслова","Дієслово","können (могти), müssen (мусити), wollen (хотіти), sollen (мати за обов'язком), dürfen (мати дозвіл), möchten (хотіла б). Модальне стоїть на другому місці, а смислове дієслово — в інфінітиві в самому кінці речення.",[["Ich kann heute nicht kommen.","Я сьогодні не можу прийти."],["Du musst mehr Deutsch sprechen.","Ти мусиш більше говорити німецькою."]],"В однині модальні змінюють голосну і НЕ мають -e/-t: ich kann, du kannst, er kann.");
r("A1","nicht чи kein","Заперечення","<b>kein</b> заперечує іменник з неозначеним артиклем або без артикля. <b>nicht</b> заперечує все інше — дієслово, прикметник, обставину, а також іменник з означеним артиклем чи присвійним.",[["Ich habe kein Auto.","У мене немає машини."],["Das ist nicht mein Auto.","Це не моя машина."]],"nicht стоїть у кінці речення, але ПЕРЕД: інфінітивом, прикметником, місцем: Ich gehe nicht ins Kino.");
r("A1","Присвійні займенники","Займенник","mein, dein, sein (його), ihr (її), unser, euer, ihr (їхній), Ihr (Ваш). Відмінюються як ein/kein: mein Vater, meine Mutter, mein Kind, meine Eltern.",[["Das ist meine Schwester.","Це моя сестра."],["Ich sehe meinen Bruder.","Я бачу свого брата."]],"Німецька не має слова «свій» — завжди повторюється потрібний займенник.");
r("A1","Відокремлювані префікси","Дієслово","Префікси an-, auf-, aus-, ein-, mit-, zu-, vor-, ab-, weg- відокремлюються і йдуть у кінець речення. Наголос падає на префікс — це і є ознака відокремлюваності.",[["Der Zug fährt um acht ab.","Потяг відходить о восьмій."],["Ich stehe jeden Tag um sechs auf.","Я встаю щодня о шостій."]],"Невідокремлювані: be-, ge-, er-, ver-, zer-, ent-, emp-, miss-. Вони ненаголошені: verstehen → ich verstehe.");

r("A2","Dativ","Відмінок","Давальний — непрямий додаток (кому?). der→dem, die→der, das→dem, множина→den + -n до іменника. Дієслова, що вимагають Dativ: helfen, danken, gefallen, gehören, antworten, passen, schmecken.",[["Ich helfe dem Kind.","Я допомагаю дитині."],["Das Buch gehört meiner Schwester.","Книга належить моїй сестрі."]],"Прийменники завжди з Dativ: aus, bei, mit, nach, seit, von, zu, gegenüber. Вивчити як пісеньку.");
r("A2","Wechselpräpositionen","Прийменник","Дев'ять прийменників беруть два відмінки: in, an, auf, über, unter, vor, hinter, neben, zwischen. <b>Wohin?</b> (рух, куди) → Akkusativ. <b>Wo?</b> (місце, де) → Dativ.",[["Ich gehe in die Küche.","Іду на кухню. (куди → Akk.)"],["Ich bin in der Küche.","Я на кухні. (де → Dat.)"]],"Питання «куди» ставиться до дії, а не до дієслова руху: Ich hänge das Bild an die Wand.");
r("A2","Perfekt","Час","Головне минуле в розмові: haben/sein + Partizip II у кінці. Слабкі: ge- + основа + -t (machen → gemacht). Сильні: ge- + основа + -en, часто зі зміною голосної (sprechen → gesprochen).",[["Ich habe das Buch gelesen.","Я прочитала книгу."],["Wir sind nach Berlin gefahren.","Ми поїхали до Берліна."]],"sein беруть дієслова руху й зміни стану: gehen, fahren, kommen, laufen, aufstehen, einschlafen, sterben, sein, bleiben, werden.");
r("A2","Präteritum","Час","Письмове минуле. У розмові вживається лише для sein, haben і модальних — решту витісняє Perfekt. war, hatte, konnte, musste, wollte, sollte, durfte.",[["Ich war gestern müde.","Я вчора була втомлена."],["Wir hatten keine Zeit.","У нас не було часу."]],"«Ich war» — правильно; «ich bin gewesen» теж можливо, але звучить важче.");
r("A2","Підрядні речення","Синтаксис","Після weil, dass, wenn, ob, obwohl, damit дієслово йде в САМИЙ КІНЕЦЬ. Це другий великий поріг після «дієслово на другому місці».",[["Ich lerne Deutsch, weil ich in Wien arbeiten will.","Вчу німецьку, бо хочу працювати у Відні."],["Ich weiß nicht, ob er kommt.","Не знаю, чи він прийде."]],"Якщо підрядне стоїть першим, головне починається з дієслова: Weil es regnet, bleibe ich zu Hause.");
r("A2","Ступені порівняння","Прикметник","-er і -sten: klein → kleiner → am kleinsten. Односкладові часто з умлаутом: alt → älter → am ältesten. Неправильні: gut/besser/am besten, viel/mehr/am meisten, gern/lieber/am liebsten, hoch/höher, nah/näher.",[["Berlin ist größer als Wien.","Берлін більший за Відень."],["Sie spricht am besten.","Вона говорить найкраще."]],"Порівняння: «як» = wie (so groß wie), «ніж» = als (größer als).");
r("A2","Зворотні дієслова","Дієслово","sich freuen, sich waschen, sich interessieren. Зворотний займенник в Akkusativ: mich, dich, sich, uns, euch, sich. Якщо є прямий додаток — зворотний стає Dativ: ich wasche mir die Hände.",[["Ich freue mich auf den Sommer.","Чекаю з нетерпінням на літо."],["Setz dich, bitte.","Сідай, будь ласка."]],"Список зворотних у німецькій і українській не збігається: sich erholen, але «відпочивати» без -ся.");
r("A2","Наказовий спосіб","Дієслово","du: основа без закінчення (Komm!, Geh!, Sprich!). ihr: форма як у теперішньому (Kommt!). Sie: інфінітив + Sie (Kommen Sie!).",[["Mach die Tür zu!","Зачини двері!"],["Warten Sie bitte einen Moment.","Зачекайте, будь ласка, хвилинку."]],"Ввічливість додається словом bitte й часом mal: Komm mal her.");
r("A2","Відмінювання прикметника: початок","Прикметник","Прикметник перед іменником завжди має закінчення. Після означеного артикля в Nominativ: -e для всіх родів, -en у множині; в Akkusativ чол. роду: -en.",[["der große Tisch, die kleine Lampe, das neue Buch","великий стіл, маленька лампа, нова книга"],["Ich sehe den großen Tisch.","Я бачу великий стіл."]],"Прикметник ПІСЛЯ іменника не змінюється ніколи: Der Tisch ist groß.");
r("A2","Порядок додатків","Синтаксис","Правило: Dativ перед Akkusativ, АЛЕ якщо додаток — займенник, він іде першим. Обставини йдуть у порядку: час → причина → спосіб → місце (TeKaMoLo).",[["Ich gebe dem Kind das Buch.","Я даю дитині книгу."],["Ich gebe es dem Kind.","Я даю її дитині."]],"Займенник завжди тисне вліво — це проста механіка, її досить запам'ятати раз.");

r("B1","Відмінювання прикметника: система","Прикметник","Три схеми. <b>Після означеного артикля</b> (der/die/das) — слабка: -e / -en. <b>Після ein/kein/mein</b> — мішана: прикметник бере закінчення артикля там, де сам артикль його не показує (ein guter Mann, ein gutes Kind). <b>Без артикля</b> — сильна: прикметник бере закінчення означеного артикля (guter Wein, kaltes Wasser).",[["ein guter Freund / der gute Freund / guter Freund","добрий друг у трьох схемах"],["mit kaltem Wasser","холодною водою"]],"Логіка одна: рід і відмінок мають бути показані хоч раз. Якщо їх показав артикль — прикметник розслабляється (-e/-en).");
r("B1","Genitiv","Відмінок","Родовий — належність. der/das → des + -s (des Mannes, des Kindes), die → der. Прийменники: während, wegen, trotz, statt, innerhalb, außerhalb.",[["das Auto meines Bruders","автомобіль мого брата"],["während des Krieges","під час війни"]],"У розмові Genitiv часто замінюють на von + Dativ: das Auto von meinem Bruder. Це нормально усно, але не в письмі.");
r("B1","Konjunktiv II","Спосіб","Ввічливість, побажання, нереальне. Найчастіші: wäre, hätte, könnte, würde, sollte, müsste. Для більшості дієслів — würde + інфінітив.",[["Könnten Sie mir bitte helfen?","Чи могли б Ви мені допомогти?"],["Wenn ich Zeit hätte, würde ich reisen.","Якби я мала час, я б подорожувала."]],"Без Konjunktiv II німецька звучить різко. Це не «додаткова тема», а базова ввічливість.");
r("B1","Relativsätze","Синтаксис","Підрядні означальні. Займенник = артикль іменника, але Dativ множини = denen, Genitiv = dessen/deren. Відмінок визначається роллю в ПІДРЯДНОМУ реченні, а рід — словом у головному.",[["Der Mann, der dort steht, ist mein Chef.","Чоловік, який там стоїть, — мій начальник."],["Die Frau, mit der ich sprach, ist Ärztin.","Жінка, з якою я говорила, — лікарка."]],"Дієслово в кінці підрядного, кома обов'язкова.");
r("B1","Passiv Präsens","Стан","werden + Partizip II. Виконавець вводиться через von (особа) або durch (засіб). Пасив вживається там, де дія важливіша за виконавця — у німецькій набагато частіше, ніж в українській.",[["Das Haus wird renoviert.","Будинок ремонтують."],["Der Brief wurde von ihr geschrieben.","Лист був написаний нею."]],"Не плутай: «ist renoviert» — стан (уже відремонтований), «wird renoviert» — процес.");
r("B1","Інфінітив із zu","Синтаксис","Після більшості дієслів, прикметників і іменників інфінітив іде з zu в кінці: Ich habe vor, nach Wien zu ziehen. У відокремлюваних дієсловах zu вставляється всередину: aufzustehen.",[["Es ist wichtig, jeden Tag zu üben.","Важливо вправлятися щодня."],["Ich versuche, früher aufzustehen.","Намагаюся вставати раніше."]],"Без zu — після модальних, sehen, hören, lassen, gehen: Ich gehe schwimmen.");
r("B1","Дієслова з фіксованими прийменниками","Лексика","Прийменник при дієслові не перекладається логічно — його треба вчити разом із дієсловом: warten AUF, denken AN, sich freuen ÜBER. Питання утворюється через wo(r)- : Worauf wartest du?",[["Ich denke oft an dich.","Я часто думаю про тебе."],["Worüber sprecht ihr?","Про що ви говорите?"]],"Замість «про це» кажуть darüber, «на це» — darauf. Ця конструкція обов'язкова, а не стилістична.");
r("B1","Часові підрядні","Синтаксис","<b>als</b> — одна подія в минулому. <b>wenn</b> — повторювана дія або майбутнє. <b>nachdem</b> — після того як (з зсувом часу). <b>bevor</b>, <b>während</b>, <b>seitdem</b>, <b>bis</b>.",[["Als ich ein Kind war, wohnte ich in Lwiw.","Коли я була дитиною, жила у Львові."],["Immer wenn es regnet, bleibe ich zu Hause.","Щоразу коли йде дощ, я лишаюся вдома."]],"Плутанина als/wenn — класична помилка. Одноразове минуле = завжди als.");
r("B1","Plusquamperfekt","Час","Передминулий: hatte/war + Partizip II. Вживається майже виключно з nachdem, щоб показати, що одна подія була раніше за іншу.",[["Nachdem ich gegessen hatte, ging ich spazieren.","Поївши, я пішла гуляти."],["Sie war schon gegangen, als ich ankam.","Вона вже пішла, коли я прибула."]]);
r("B1","Futur I","Час","werden + інфінітив. Але майбутнє в німецькій частіше виражають теперішнім часом з обставиною. Futur I радше означає припущення або тверде рішення.",[["Morgen fahre ich nach Wien.","Завтра я їду до Відня. (звичайне майбутнє)"],["Er wird wohl krank sein.","Він, мабуть, хворий. (припущення)"]]);

r("B2","Passiv у всіх часах","Стан","Präteritum: wurde + P.II. Perfekt: ist + P.II + worden. Plusquamperfekt: war + P.II + worden. З модальним: muss … werden.",[["Das Problem ist gelöst worden.","Проблему було розв'язано."],["Der Antrag muss bis Freitag eingereicht werden.","Заяву треба подати до п'ятниці."]],"У Perfekt-пасиві саме worden, а не geworden. Це маркер рівня.");
r("B2","Passiversatzformen","Стан","Замінники пасиву в діловій мові: <b>sein + zu + Inf.</b> (необхідність), <b>sich lassen + Inf.</b> (можливість), <b>-bar</b> (властивість), <b>man</b>.",[["Das Problem lässt sich lösen.","Проблему можна розв'язати."],["Die Regeln sind einzuhalten.","Правил слід дотримуватися."]]);
r("B2","Konjunktiv I","Спосіб","Непряма мова в пресі та звітах: er sei, er habe, er komme. Показує, що це чужі слова і мовець за них не ручається.",[["Er sagte, er sei krank.","Він сказав, що хворий."],["Sie behauptet, sie habe nichts gewusst.","Вона стверджує, що нічого не знала."]],"Якщо форма Konjunktiv I збігається з індикативом, беруть Konjunktiv II: sie hätten замість sie haben.");
r("B2","Partizip як означення","Синтаксис","Partizip I (-end) = активна одночасна дія; Partizip II = пасивна завершена. Стоять перед іменником і відмінюються як прикметники — основа німецького письмового стилю.",[["das lachende Kind","дитина, яка сміється"],["die gestern getroffene Entscheidung","рішення, ухвалене вчора"]],"Це стискає ціле підрядне в одне означення — тому преса ним рясніє.");
r("B2","Nominalstil","Стиль","У формальній німецькій дієслова перетворюють на іменники: prüfen → die Prüfung, entscheiden → die Entscheidung. Речення стає щільнішим і сухішим.",[["nach der Prüfung der Unterlagen","після перевірки документів"],["aufgrund der gestiegenen Kosten","через зрослі витрати"]],"Для іспиту треба вміти в обидва боки: розгортати номінальне в дієслівне і навпаки.");
r("B2","n-Deklination","Іменник","Група іменників чол. роду бере -n/-en в усіх відмінках крім Nominativ: der Junge/den Jungen, der Kunde, der Kollege, der Mensch, der Nachbar, der Student, der Praktikant, der Herr.",[["Ich kenne den Studenten.","Я знаю цього студента."],["Ich helfe dem Kollegen.","Я допомагаю колезі."]],"Помилка «Ich kenne den Student» одразу видає рівень нижче B2.");
r("B2","Konnektoren двоскладові","Синтаксис","zwar … aber, entweder … oder, weder … noch, nicht nur … sondern auch, je … desto. Кожен впливає на порядок слів по-своєму: після je йде дієслово в кінець, після desto — на друге місце.",[["Je mehr ich lerne, desto besser verstehe ich.","Чим більше вчу, тим краще розумію."],["Er ist zwar müde, aber er arbeitet weiter.","Він хоч і втомлений, але працює далі."]]);
r("B2","Керування дієслів і прикметників","Лексика","На B2 керування треба знати системно, включно з прикметниками: stolz auf, abhängig von, interessiert an, verantwortlich für, zufrieden mit, bereit zu.",[["Ich bin stolz auf dich.","Я тобою пишаюся."],["Das hängt von vielen Faktoren ab.","Це залежить від багатьох факторів."]]);
r("B2","Заперечні й обмежувальні звороти","Синтаксис","kaum (заледве), keineswegs, nicht einmal, außer, es sei denn, geschweige denn. Використовуються для точних нюансів у аргументації.",[["Er hat kaum etwas gesagt.","Він майже нічого не сказав."],["Ich komme, es sei denn, es regnet.","Я прийду, хіба що піде дощ."]]);
r("B2","Порядок слів у складному реченні","Синтаксис","У підрядному з модальним чи перфектом допоміжне дієслово йде в самий кінець. При подвійному інфінітиві — навпаки, воно виходить наперед.",[["…, weil ich es nicht machen konnte.","…бо я не могла цього зробити."],["…, weil ich es nicht habe machen können.","…бо я не змогла цього зробити."]],"Друга конструкція (Ersatzinfinitiv) — маркер C1.");

r("C1","Konjunktiv II минулого","Спосіб","Нереальне в минулому: hätte/wäre + Partizip II. З модальним — подвійний інфінітив: hätte machen können. Це основа висловлення жалю й докору.",[["Wenn ich das gewusst hätte, wäre ich nicht gekommen.","Якби я це знала, я б не прийшла."],["Du hättest mich anrufen können.","Ти міг би мені зателефонувати."]],"Без цієї форми неможливо говорити про альтернативне минуле — а це половина дорослих розмов.");
r("C1","Funktionsverbgefüge","Стиль","Стійкі зв'язки «дієслово + іменник», де значення несе іменник: in Betracht ziehen, zur Verfügung stellen, Kritik üben, eine Entscheidung treffen. Ознака зрілого письмового стилю.",[["Wir müssen diese Option in Betracht ziehen.","Ми маємо розглянути цей варіант."],["Der Bericht steht zur Verfügung.","Звіт доступний."]],"Замінити їх простим дієсловом можна — але текст одразу впаде до B1.");
r("C1","Modalpartikeln","Розмова","doch, ja, mal, eben, halt, wohl, denn, schon, ruhig. Не перекладаються словниково — передають ставлення мовця. Саме вони роблять мову живою, а їх відсутність — «правильною, але роботизованою».",[["Komm doch mal vorbei!","Та заскоч якось!"],["Das ist eben so.","Ну так уже воно є."]],"Вчити тільки з контексту й інтонацією. Ніколи не перекладай їх окремо.");
r("C1","Складні атрибути","Синтаксис","Розгорнуте означення перед іменником: der von der Regierung im letzten Jahr beschlossene Plan. Читати треба з кінця: спершу іменник, потім означення.",[["die in den letzten Jahren stark gestiegenen Preise","ціни, які сильно зросли за останні роки"],["ein kaum zu lösendes Problem","проблема, яку заледве можна розв'язати"]],"Конструкція zu + Partizip I означає пасивну можливість або необхідність.");
r("C1","Стилістичні регістри","Стиль","Одна думка звучить по-різному: розмовно (Das nervt), нейтрально (Das stört mich), формально (Dies stellt eine erhebliche Beeinträchtigung dar). На C1 оцінюють саме вміння перемикатися.",[["Ich hab keinen Bock.","Мені не хочеться. (розм.)"],["Ich sehe davon ab.","Я від цього утримаюся. (форм.)"]]);
r("C1","Синонімія й нюанси","Лексика","Ряди на кшталт sagen — behaupten — einräumen — beteuern — andeuten розрізняються не значенням, а позицією мовця. На C1 помилка вибору синоніма важча за граматичну.",[["Er räumte ein, dass er Fehler gemacht hatte.","Він визнав, що припустився помилок."],["Er unterstellte ihr böse Absicht.","Він приписав їй злий намір."]]);
r("C1","Емфатичний порядок слів","Синтаксис","Винесення елемента на перше місце змінює акцент. Також Inversion після ausgerechnet, kaum, nur, erst, nicht nur — після них іде дієслово.",[["Kaum war ich zu Hause, klingelte das Telefon.","Щойно я була вдома, задзвонив телефон."],["Nur so lässt sich das erklären.","Тільки так це можна пояснити."]]);
r("C1","Номіналізація і денаміналізація","Стиль","Уміння згорнути підрядне в іменникову групу і навпаки — головна вправа C1-письма: «weil die Kosten gestiegen sind» → «wegen der gestiegenen Kosten».",[["nach Abschluss der Verhandlungen","після завершення переговорів"],["trotz wiederholter Aufforderung","попри неодноразову вимогу"]]);
r("C1","Ідіоматика","Лексика","Стійкі вирази не розкладаються на слова: den Nagel auf den Kopf treffen, ins Fettnäpfchen treten. На C1 очікується їх розуміння в мовленні і помірне вживання у власному.",[["Damit hast du den Nagel auf den Kopf getroffen.","Ти влучила в саму суть."],["Er wirft die Flinte ins Korn.","Він опускає руки."]],"Помірність важлива: надлишок ідіом звучить неприродно, як у підручнику.");
r("C1","Текстова зв'язність","Стиль","На C1 оцінюють не речення, а текст: логічні переходи (dementsprechend, gleichwohl, insofern), тематична прогресія, уникнення повторів через синоніми й займенники.",[["Insofern lässt sich festhalten, dass …","Остільки можна констатувати, що …"],["Gleichwohl bleibt fraglich, ob …","Попри це лишається сумнівним, чи …"]]);

r("A1","Особові займенники","Займенник","ich, du, er/sie/es, wir, ihr, sie/Sie. В Akkusativ: mich, dich, ihn, sie, es, uns, euch, sie. В Dativ: mir, dir, ihm, ihr, ihm, uns, euch, ihnen. <b>Sie</b> з великої літери — ввічлива форма до незнайомих і в установах.",[["Kannst du mir helfen?","Можеш мені допомогти?"],["Ich sehe ihn nicht.","Я його не бачу."]],"До людей старших чи незнайомих — завжди Sie, поки вам не запропонують перейти на du.");
r("A1","es gibt","Конструкція","«Є, існує» передається через es gibt + Akkusativ — незалежно від числа. Це одна з найчастіших конструкцій у мові.",[["Es gibt hier ein gutes Restaurant.","Тут є хороший ресторан."],["Es gibt keine Probleme.","Проблем немає."]],"Не «hier ist ein Restaurant» у значенні «тут є» — це буде «ось ресторан».");
r("A1","Множина іменників","Іменник","П'ять типів: -e (der Tisch/Tische), -er (das Kind/Kinder), -n/-en (die Frau/Frauen), -s (das Auto/Autos), без змін (das Fenster/Fenster). Часто додається умлаут. Множину треба вчити разом зі словом.",[["ein Buch → zwei Bücher","одна книга → дві книги"],["die Frau → die Frauen","жінка → жінки"]],"Артикль множини завжди die, а в Dativ множини іменник ще й отримує -n: mit den Kindern.");
r("A1","Прийменники місця й часу","Прийменник","<b>in</b> — у місті/країні: in Berlin. <b>nach</b> — до міста чи країни без артикля: nach Wien. <b>zu</b> — до особи чи закладу: zum Arzt. <b>an</b> — дні й частини доби: am Montag, am Abend. <b>um</b> — година: um acht. <b>im</b> — місяці й пори року: im Mai.",[["Ich fahre nach Deutschland.","Я їду до Німеччини."],["Ich gehe zum Arzt.","Я йду до лікаря."]],"Виняток: in die Schweiz, in die Türkei — країни з артиклем беруть in.");
r("A1","Числа й час","Лексика","Числа читаються «навиворіт»: 21 = einundzwanzig (один-і-двадцять). Час: Viertel nach drei (чверть по третій), halb vier (пів на четверту — увага, це 3:30!), Viertel vor vier.",[["Es ist halb sieben.","Пів на сьому, тобто 6:30."],["siebenundvierzig","сорок сім"]],"«halb sieben» — найтиповіша помилка: німці рахують до наступної години, як і українці, але легко переплутати.");

r("A2","Прийменники з Genitiv","Прийменник","während (під час), wegen (через), trotz (попри), statt (замість), innerhalb (у межах), außerhalb (поза). У розмові часто вживають з Dativ, але в письмі — Genitiv.",[["wegen des schlechten Wetters","через погану погоду"],["trotz der Kosten","попри витрати"]]);
r("A2","werden","Дієслово","Три ролі: самостійне дієслово «ставати» (Ich werde Ärztin), допоміжне для майбутнього (Ich werde kommen), допоміжне для пасиву (Das wird gemacht). Форми: ich werde, du wirst, er wird.",[["Es wird kalt.","Холоднішає."],["Sie wird Lehrerin.","Вона стає вчителькою."]],"Не плутай werden (ставати) з bekommen (отримувати) — false friend для англомовних.");
r("A2","Порядок TeKaMoLo","Синтаксис","Обставини йдуть у порядку: <b>Te</b>mporal (коли) → <b>Ka</b>usal (чому) → <b>Mo</b>dal (як) → <b>Lo</b>kal (де). Це не жорсткий закон, але порушення звучить дивно.",[["Ich fahre morgen wegen der Arbeit mit dem Zug nach Berlin.","Я їду завтра через роботу потягом до Берліна."]],"Українська ставить місце раніше — тому мозок опирається. Вправлятися свідомо.");
r("A2","Неозначені займенники","Займенник","man (загальне «люди/ти»), jemand/niemand, etwas/nichts, alle/alles, jeder, einige, mehrere. <b>man</b> — надзвичайно частий: замінює безособові речення.",[["Hier darf man nicht rauchen.","Тут не можна курити."],["Man sagt, dass …","Кажуть, що …"]],"man вимагає дієслова в 3 особі однини: man geht, man macht.");
r("A2","Прикметник як іменник","Іменник","Прикметники й дієприкметники стають іменниками: der Deutsche, der Angestellte, der Bekannte, das Beste. Вони й далі відмінюються як прикметники.",[["ein Bekannter von mir","один мій знайомий"],["Das ist das Beste.","Це найкраще."]],"Тому «ein Deutscher», але «der Deutsche» — закінчення міняється разом з артиклем.");

r("B1","Konjunktiv II: реальні vs нереальні умови","Спосіб","Реальна умова — індикатив із wenn. Нереальна — Konjunktiv II. Це різниця між «якщо матиму час» і «якби я мала час».",[["Wenn ich Zeit habe, komme ich.","Якщо матиму час — прийду."],["Wenn ich Zeit hätte, käme ich.","Якби я мала час, я б прийшла."]],"У розмові замість käme частіше würde kommen — обидва правильні.");
r("B1","Займенникові прислівники","Синтаксис","Замість «прийменник + це/те» вживається da(r)- : darauf, damit, dafür, davon, darüber. Питання — wo(r)- : worauf, womit, wofür.",[["Ich freue mich darauf.","Я цьому радію (наперед)."],["Womit kann ich helfen?","Чим я можу допомогти?"]],"Ця форма застосовується ТІЛЬКИ до речей. Для людей — звичайний прийменник: auf ihn, mit ihr.");
r("B1","Подвійні сполучники","Синтаксис","je … desto (з дієсловом у кінці після je), entweder … oder, weder … noch, sowohl … als auch, nicht nur … sondern auch, zwar … aber.",[["Sowohl er als auch sie kommen.","І він, і вона прийдуть."],["Weder er noch sie hat angerufen.","Ні він, ні вона не подзвонили."]]);
r("B1","Непряме питання","Синтаксис","Питання всередині речення стає підрядним: дієслово в кінець. Якщо немає питального слова — вживається <b>ob</b>.",[["Ich weiß nicht, wo er wohnt.","Не знаю, де він живе."],["Sie fragt, ob wir kommen.","Вона питає, чи ми прийдемо."]],"«Ich weiß nicht, wo wohnt er» — типова помилка. Дієслово завжди в кінці.");
r("B1","lassen","Дієслово","Чотири значення: залишати, дозволяти, доручати (щоб хтось зробив), а також sich lassen = «можна». У перфекті — подвійний інфінітив: Ich habe es machen lassen.",[["Ich lasse mir die Haare schneiden.","Я стрижуся (даю підстригти)."],["Das lässt sich machen.","Це можна зробити."]],"Друга конструкція — основа ділової німецької, вивчити обов'язково.");

r("B2","Modalverben суб'єктивні","Спосіб","Модальні виражають не дію, а ступінь упевненості мовця: müssen (напевно), dürfte (ймовірно), können (можливо), sollen (кажуть, що), wollen (стверджує, що).",[["Er muss krank sein.","Він, напевно, хворий."],["Sie soll sehr reich sein.","Кажуть, вона дуже багата."]],"«Er will Arzt sein» = він стверджує, що лікар (а мовець сумнівається). Це не «хоче бути».");
r("B2","Konjunktiv I у деталях","Спосіб","Утворюється від інфінітива: er sage, er habe, er sei, er komme. Для мовлення про минуле: er habe gemacht, er sei gekommen. Обов'язкова форма журналістики й наукових оглядів.",[["Der Minister erklärte, die Lage sei stabil.","Міністр заявив, що ситуація стабільна."],["Sie sagte, sie habe nichts gesehen.","Вона сказала, що нічого не бачила."]]);
r("B2","Genitivattribute й ланцюжки","Стиль","Німецька преса нанизує генітиви: die Auswirkungen der Entscheidung der Regierung. Читається справа наліво. Уміння розплутувати такі ланцюжки — базова навичка B2.",[["die Folgen der Erhöhung der Preise","наслідки підвищення цін"]],"У власному письмі більше двох генітивів поспіль краще не робити — стає нечитабельно.");
r("B2","Konzessive конструкції","Синтаксис","Поступка: obwohl, obgleich, wenngleich (підрядне), trotzdem, dennoch, gleichwohl (головне), trotz + Gen. (прийменник), auch wenn (навіть якщо).",[["Auch wenn es regnet, gehen wir.","Навіть якщо піде дощ, ми йдемо."],["Er kam dennoch zu spät.","Він усе одно спізнився."]],"Помилка: після trotzdem дієслово на другому місці, після obwohl — у кінці.");
r("B2","Сталі прийменникові звороти","Стиль","in Bezug auf, im Vergleich zu, im Gegensatz zu, im Zusammenhang mit, im Hinblick auf, aufgrund von, mit Blick auf. Основа зв'язного письмового тексту.",[["Im Vergleich zum Vorjahr sind die Zahlen gestiegen.","Порівняно з минулим роком цифри зросли."],["In Bezug auf die Kosten …","Щодо витрат …"]]);

r("C1","Ersatzinfinitiv","Синтаксис","Подвійний інфінітив: у перфекті модальних і lassen, sehen, hören замість Partizip II стоїть інфінітив. У підрядному допоміжне дієслово виходить наперед.",[["Ich habe nicht kommen können.","Я не змогла прийти."],["…, weil ich nicht habe kommen können.","…бо я не змогла прийти."]],"Винесення habe вперед у підрядному — чіткий маркер C1. Помилка тут одразу знижує рівень.");
r("C1","Пасив із модальними в усіх часах","Стан","muss gemacht werden → musste gemacht werden → hat gemacht werden müssen. Конструкція перевантажена, але в офіційних текстах трапляється постійно.",[["Der Antrag hätte früher gestellt werden müssen.","Заяву треба було подати раніше."]],"Розбирати такі речення варто з кінця: müssen → werden → gestellt.");
r("C1","Nominalstil ↔ Verbalstil","Стиль","Головна вправа C1-письма: перетворювати підрядні на іменникові групи й навпаки. Іспит перевіряє саме це вміння в обидва боки.",[["weil die Preise gestiegen sind → wegen gestiegener Preise","бо ціни зросли → через зрослі ціни"],["nach Beendigung der Arbeit → nachdem die Arbeit beendet worden war","після завершення роботи"]]);
r("C1","Порядок слів для акценту","Синтаксис","Рема (нове) тяжіє до кінця речення, тема (відоме) — до початку. Винесення додатка на перше місце створює наголос. Після nur, erst, kaum, nicht nur йде інверсія.",[["Diesen Fehler habe ich nicht gemacht.","Цієї помилки я не робила."],["Erst dann wurde klar, worum es ging.","Лише тоді стало ясно, про що йшлося."]]);
r("C1","Регістри й дистанція","Стиль","Німецька дуже чітко розділяє: Umgangssprache (розмовна), Standardsprache (нейтральна), Amtssprache (канцелярська), gehobene Sprache (висока). Плутання регістрів на C1 — важча помилка, ніж граматична.",[["Ich hab kein Bock. / Ich möchte nicht. / Ich sehe davon ab.","три регістри однієї думки"]],"На іспиті і в житті: канцелярит у розмові звучить смішно, розмовне в листі — грубо.");

