const V = {};
V.A1 = {
"Люди й сім'я":`der Vater|¨|батько;die Mutter|¨|мати;der Sohn|¨-e|син;die Tochter|¨|донька;der Bruder|¨|брат;die Schwester|-n|сестра;die Eltern|—|батьки;das Kind|-er|дитина;der Mann|¨-er|чоловік;die Frau|-en|жінка, дружина;der Freund|-e|друг;die Freundin|-nen|подруга;der Junge|-n|хлопець;das Mädchen|-|дівчинка;die Familie|-n|сім'я;der Opa|-s|дідусь;die Oma|-s|бабуся;der Nachbar|-n|сусід;der Name|-n|ім'я;die Leute|—|люди`,
"Числа й час":`die Zahl|-en|число;die Uhr|-en|годинник;die Stunde|-n|година;die Minute|-n|хвилина;der Tag|-e|день;die Woche|-n|тиждень;der Monat|-e|місяць;das Jahr|-e|рік;heute|—|сьогодні;morgen|—|завтра;gestern|—|вчора;jetzt|—|зараз;früh|—|рано;spät|—|пізно;der Morgen|-|ранок;der Abend|-e|вечір;die Nacht|¨-e|ніч;der Mittag|-e|полудень;das Datum|Daten|дата;die Zeit|-en|час`,
"Дім і речі":`das Haus|¨-er|дім;die Wohnung|-en|квартира;das Zimmer|-|кімната;die Küche|-n|кухня;das Bad|¨-er|ванна;das Bett|-en|ліжко;der Tisch|-e|стіл;der Stuhl|¨-e|стілець;die Tür|-en|двері;das Fenster|-|вікно;der Schrank|¨-e|шафа;die Lampe|-n|лампа;der Schlüssel|-|ключ;die Wand|¨-e|стіна;das Sofa|-s|диван;der Spiegel|-|дзеркало;die Treppe|-n|сходи;der Garten|¨|сад;die Miete|-n|орендна плата;der Müll|—|сміття`,
"Їжа й напої":`das Brot|-e|хліб;die Butter|—|масло;der Käse|-|сир;das Ei|-er|яйце;das Fleisch|—|м'ясо;der Fisch|-e|риба;das Gemüse|-|овочі;das Obst|—|фрукти;der Apfel|¨|яблуко;die Kartoffel|-n|картопля;die Milch|—|молоко;das Wasser|-|вода;der Kaffee|-s|кава;der Tee|-s|чай;das Bier|-e|пиво;der Wein|-e|вино;der Zucker|—|цукор;das Salz|-e|сіль;die Suppe|-n|суп;der Reis|—|рис`,
"Місто й дорога":`die Stadt|¨-e|місто;das Dorf|¨-er|село;die Straße|-n|вулиця;der Platz|¨-e|площа;der Bahnhof|¨-e|вокзал;der Flughafen|¨|аеропорт;die Haltestelle|-n|зупинка;der Bus|-se|автобус;der Zug|¨-e|потяг;das Auto|-s|автомобіль;das Fahrrad|¨-er|велосипед;die Bank|-en|банк;die Post|—|пошта;das Geschäft|-e|магазин;der Markt|¨-e|ринок;die Apotheke|-n|аптека;das Krankenhaus|¨-er|лікарня;die Schule|-n|школа;die Kirche|-n|церква;der Park|-s|парк`,
"Одяг і покупки":`die Kleidung|—|одяг;das Hemd|-en|сорочка;die Hose|-n|штани;der Rock|¨-e|спідниця;das Kleid|-er|сукня;der Schuh|-e|черевик;die Jacke|-n|куртка;der Mantel|¨|пальто;die Mütze|-n|шапка;die Tasche|-n|сумка;das T-Shirt|-s|футболка;der Preis|-e|ціна;das Geld|—|гроші;die Kasse|-n|каса;die Größe|-n|розмір;kaufen|—|купувати;kosten|—|коштувати;bezahlen|—|платити;billig|—|дешевий;teuer|—|дорогий`,
"Тіло і здоров'я":`der Kopf|¨-e|голова;das Auge|-n|око;das Ohr|-en|вухо;die Nase|-n|ніс;der Mund|¨-er|рот;die Hand|¨-e|кисть руки;der Arm|-e|рука;das Bein|-e|нога;der Fuß|¨-e|стопа;der Rücken|-|спина;der Bauch|¨-e|живіт;das Herz|-en|серце;der Zahn|¨-e|зуб;das Haar|-e|волосся;der Arzt|¨-e|лікар;die Krankheit|-en|хвороба;der Schmerz|-en|біль;das Fieber|—|температура;gesund|—|здоровий;krank|—|хворий`,
"Базові дієслова":`sein|—|бути;haben|—|мати;machen|—|робити;gehen|—|йти;kommen|—|приходити;sehen|—|бачити;hören|—|чути;sprechen|—|розмовляти;sagen|—|казати;essen|—|їсти;trinken|—|пити;schlafen|—|спати;wohnen|—|мешкати;arbeiten|—|працювати;lernen|—|вчити;lesen|—|читати;schreiben|—|писати;fahren|—|їхати;nehmen|—|брати;geben|—|давати`,
"Базові прикметники":`gut|—|добрий;schlecht|—|поганий;groß|—|великий;klein|—|малий;neu|—|новий;alt|—|старий;jung|—|молодий;schön|—|гарний;lang|—|довгий;kurz|—|короткий;warm|—|теплий;kalt|—|холодний;schnell|—|швидкий;langsam|—|повільний;richtig|—|правильний;falsch|—|неправильний;einfach|—|простий;schwer|—|важкий;wichtig|—|важливий;müde|—|втомлений`,
"Службові слова":`und|—|і;aber|—|але;oder|—|або;weil|—|тому що;dass|—|що (сполучник);wenn|—|якщо, коли;nicht|—|не;kein|—|жоден, ніякий;auch|—|також;noch|—|ще;schon|—|вже;immer|—|завжди;nie|—|ніколи;oft|—|часто;manchmal|—|іноді;sehr|—|дуже;viel|—|багато;wenig|—|мало;hier|—|тут;dort|—|там`
};
V.A2 = {
"Робота й професії":`der Beruf|-e|професія;die Arbeit|-en|робота;der Chef|-s|начальник;die Kollegin|-nen|колега (ж.);das Büro|-s|офіс;die Firma|Firmen|фірма;der Vertrag|¨-e|договір;das Gehalt|¨-er|зарплата;die Stelle|-n|посада, вакансія;die Bewerbung|-en|заява на роботу;der Lebenslauf|¨-e|резюме;der Termin|-e|призначена зустріч;die Besprechung|-en|нарада;die Aufgabe|-n|завдання;der Kunde|-n|клієнт;die Erfahrung|-en|досвід;die Ausbildung|-en|фахова освіта;der Praktikant|-en|практикант;verdienen|—|заробляти;kündigen|—|звільнятися, розривати`,
"Гроші й покупки":`das Konto|Konten|рахунок у банку;die Rechnung|-en|рахунок до оплати;die Quittung|-en|квитанція;die Steuer|-n|податок;die Versicherung|-en|страхування;der Rabatt|-e|знижка;das Angebot|-e|пропозиція;die Ware|-n|товар;der Verkäufer|-|продавець;die Bestellung|-en|замовлення;die Lieferung|-en|доставка;die Kreditkarte|-n|кредитна картка;überweisen|—|переказувати;sparen|—|заощаджувати;ausgeben|—|витрачати;leihen|—|позичати;umtauschen|—|обміняти;bar|—|готівкою;kostenlos|—|безкоштовний;günstig|—|вигідний за ціною`,
"Подорож":`die Reise|-n|подорож;der Urlaub|-e|відпустка;das Ticket|-s|квиток;der Fahrplan|¨-e|розклад;die Verspätung|-en|запізнення;der Koffer|-|валіза;das Gepäck|—|багаж;die Unterkunft|¨-e|помешкання;das Hotel|-s|готель;die Buchung|-en|бронювання;der Ausweis|-e|посвідчення;der Reisepass|¨-e|закордонний паспорт;die Grenze|-n|кордон;die Richtung|-en|напрямок;die Sehenswürdigkeit|-en|пам'ятка;umsteigen|—|пересідати;abfahren|—|відʼїжджати;ankommen|—|прибувати;buchen|—|бронювати;besichtigen|—|оглядати`,
"Погода й природа":`das Wetter|-|погода;die Sonne|-n|сонце;der Regen|-|дощ;der Schnee|—|сніг;der Wind|-e|вітер;die Wolke|-n|хмара;der Nebel|-|туман;das Gewitter|-|гроза;die Temperatur|-en|температура;der Himmel|-|небо;der Baum|¨-e|дерево;der Wald|¨-er|ліс;die Blume|-n|квітка;das Gras|¨-er|трава;der Berg|-e|гора;der See|-n|озеро;das Meer|-e|море;der Fluss|¨-e|річка;die Insel|-n|острів;das Tier|-e|тварина`,
"Побут і документи":`das Formular|-e|бланк;der Antrag|¨-e|заява, клопотання;die Anmeldung|-en|реєстрація;die Behörde|-n|установа;die Unterschrift|-en|підпис;die Bescheinigung|-en|довідка;der Nachweis|-e|підтвердження;die Frist|-en|строк;die Adresse|-n|адреса;der Vermieter|-|орендодавець;die Kaution|-en|застава;die Nebenkosten|—|комунальні витрати;der Strom|—|електрика;die Heizung|-en|опалення;gültig|—|дійсний;ausfüllen|—|заповнювати;unterschreiben|—|підписувати;beantragen|—|подавати заяву;sich anmelden|—|реєструватися;abgeben|—|здавати, подавати`,
"Емоції й стосунки":`das Gefühl|-e|почуття;die Freude|-n|радість;die Angst|¨-e|страх;die Wut|—|лють;die Trauer|—|смуток;die Liebe|—|любов;die Hoffnung|-en|надія;die Beziehung|-en|стосунки;die Hochzeit|-en|весілля;die Scheidung|-en|розлучення;stolz|—|гордий;enttäuscht|—|розчарований;zufrieden|—|задоволений;nervös|—|знервований;sich freuen|—|радіти;sich ärgern|—|злитися;sich verlieben|—|закохатися;streiten|—|сваритися;sich entschuldigen|—|вибачатися;vertrauen|—|довіряти`,
"Дієслова A2":`bringen|—|приносити;holen|—|забирати;suchen|—|шукати;finden|—|знаходити;verlieren|—|губити;vergessen|—|забувати;sich erinnern|—|згадувати;versuchen|—|намагатися;schaffen|—|встигати, долати;beginnen|—|починати;beenden|—|завершувати;erklären|—|пояснювати;verstehen|—|розуміти;entscheiden|—|вирішувати;wählen|—|обирати;empfehlen|—|радити;helfen|—|допомагати;danken|—|дякувати;warten|—|чекати;treffen|—|зустрічати`,
"Прикметники A2":`freundlich|—|привітний;höflich|—|ввічливий;ehrlich|—|чесний;faul|—|лінивий;fleißig|—|старанний;ruhig|—|спокійний;laut|—|гучний;sauber|—|чистий;schmutzig|—|брудний;gefährlich|—|небезпечний;sicher|—|безпечний, впевнений;möglich|—|можливий;nötig|—|потрібний;ähnlich|—|схожий;verschieden|—|різний;bekannt|—|відомий;beliebt|—|популярний;pünktlich|—|пунктуальний;zuverlässig|—|надійний;neugierig|—|допитливий`,
"Прийменники":`mit|—|з (кимось);ohne|—|без;für|—|для;gegen|—|проти;durch|—|крізь;um|—|навколо, о (годині);bei|—|біля, у (когось);nach|—|після, до (міста);seit|—|з (певного часу);von|—|від;zu|—|до;aus|—|з (звідки);während|—|під час;wegen|—|через (причина);trotz|—|попри;zwischen|—|між;über|—|над, про;unter|—|під;vor|—|перед;hinter|—|позаду`,
"Час і послідовність":`zuerst|—|спершу;dann|—|потім;danach|—|після цього;schließlich|—|нарешті;plötzlich|—|раптом;sofort|—|негайно;bald|—|скоро;gerade|—|саме зараз;damals|—|тоді;vorher|—|раніше;nachher|—|згодом;täglich|—|щоденно;wöchentlich|—|щотижня;normalerweise|—|зазвичай;selten|—|рідко;meistens|—|переважно;gleichzeitig|—|одночасно;endlich|—|нарешті;inzwischen|—|тим часом;ständig|—|постійно`
};
V.B1 = {
"Освіта й навчання":`die Bildung|—|освіта;die Universität|-en|університет;das Studium|Studien|навчання у виші;der Studiengang|¨-e|спеціальність;die Vorlesung|-en|лекція;das Seminar|-e|семінар;die Prüfung|-en|іспит;die Note|-n|оцінка;das Zeugnis|-se|свідоцтво;der Abschluss|¨-e|диплом, завершення;die Kenntnisse|—|знання, навички;die Fähigkeit|-en|здібність;das Wissen|—|знання;der Fortschritt|-e|поступ;sich bewerben|—|подавати заявку;bestehen|—|скласти іспит;scheitern|—|зазнати невдачі;wiederholen|—|повторювати;sich vorbereiten|—|готуватися;teilnehmen|—|брати участь`,
"Кар'єра":`die Karriere|-n|кар'єра;die Beförderung|-en|підвищення;die Verantwortung|-en|відповідальність;die Leistung|-en|результат, продуктивність;die Herausforderung|-en|виклик;das Ziel|-e|мета;der Auftrag|¨-e|доручення, замовлення;die Zusammenarbeit|—|співпраця;das Team|-s|команда;die Arbeitslosigkeit|—|безробіття;das Praktikum|Praktika|стажування;die Weiterbildung|-en|підвищення кваліфікації;der Wettbewerb|-e|конкуренція;die Branche|-n|галузь;der Vorgesetzte|-n|керівник;selbstständig|—|самостійний;berufstätig|—|працевлаштований;sich durchsetzen|—|відстояти позицію;leiten|—|керувати;betreuen|—|опікуватися`,
"Житло й побут":`die Umgebung|-en|околиця;der Stadtteil|-e|район міста;die Lage|-n|розташування, ситуація;der Umzug|¨-e|переїзд;die Einrichtung|-en|облаштування;der Mietvertrag|¨-e|договір оренди;die Renovierung|-en|ремонт;der Schaden|¨|пошкодження;die Reparatur|-en|полагодження;der Hausmeister|-|управитель будинку;die Nachbarschaft|-en|сусідство;die Ordnung|-en|порядок;der Lärm|—|шум;die Ruhe|—|тиша;der Zustand|¨-e|стан;einziehen|—|заселятися;ausziehen|—|виїжджати;renovieren|—|робити ремонт;sich beschweren|—|скаржитися;besorgen|—|роздобути`,
"Здоров'я":`die Behandlung|-en|лікування;die Untersuchung|-en|обстеження;die Diagnose|-n|діагноз;das Rezept|-e|рецепт;das Medikament|-e|ліки;die Nebenwirkung|-en|побічна дія;die Ernährung|—|харчування;die Bewegung|-en|рух;der Schlaf|—|сон;der Stress|—|стрес;die Erholung|—|відновлення;die Vorsorge|—|профілактика;die Wirkung|-en|дія, ефект;die Beschwerden|—|скарги на здоров'я;sich erholen|—|відновлюватися;verschreiben|—|виписувати ліки;heilen|—|зцілювати;leiden|—|страждати;verzichten|—|відмовлятися від;belasten|—|обтяжувати`,
"Стосунки й суспільство":`die Gesellschaft|-en|суспільство;die Gemeinschaft|-en|спільнота;der Kontakt|-e|контакт;das Verhalten|—|поведінка;die Meinung|-en|думка;der Eindruck|¨-e|враження;das Vertrauen|—|довіра;der Respekt|—|повага;das Missverständnis|-se|непорозуміння;der Konflikt|-e|конфлікт;der Kompromiss|-e|компроміс;die Rücksicht|—|зважання на інших;die Unterstützung|-en|підтримка;sich verstehen|—|порозумітися;sich kümmern|—|піклуватися;beeinflussen|—|впливати;überzeugen|—|переконувати;zustimmen|—|погоджуватися;ablehnen|—|відхиляти;sich anpassen|—|пристосовуватися`,
"Технології":`das Gerät|-e|пристрій;der Bildschirm|-e|екран;die Anwendung|-en|застосунок;die Datei|-en|файл;die Daten|—|дані;das Netzwerk|-e|мережа;die Verbindung|-en|з'єднання;die Sicherheit|-en|безпека;das Passwort|¨-er|пароль;die Einstellung|-en|налаштування;die Entwicklung|-en|розробка, розвиток;die Nutzung|-en|використання;der Zugang|¨-e|доступ;die Störung|-en|збій;speichern|—|зберігати;löschen|—|видаляти;herunterladen|—|завантажувати;aktualisieren|—|оновлювати;benutzerfreundlich|—|зручний у користуванні;die künstliche Intelligenz|—|штучний інтелект`,
"Абстрактні поняття":`die Möglichkeit|-en|можливість;die Bedingung|-en|умова;die Voraussetzung|-en|передумова;die Folge|-n|наслідок;der Grund|¨-e|причина;der Zweck|-e|мета, призначення;der Unterschied|-e|різниця;die Ähnlichkeit|-en|схожість;der Zusammenhang|¨-e|взаємозв'язок;die Bedeutung|-en|значення;der Vorteil|-e|перевага;der Nachteil|-e|недолік;die Lösung|-en|рішення;das Problem|-e|проблема;die Absicht|-en|намір;die Entscheidung|-en|рішення (вибір);die Erwartung|-en|очікування;die Gewohnheit|-en|звичка;der Versuch|-e|спроба;die Ausnahme|-n|виняток`,
"Дієслова з прийменниками":`warten auf|—|чекати на;denken an|—|думати про;sich freuen auf|—|радіти майбутньому;sich freuen über|—|радіти чомусь;sich interessieren für|—|цікавитися;sich beschäftigen mit|—|займатися;sich erinnern an|—|пам'ятати про;sich gewöhnen an|—|звикати до;achten auf|—|звертати увагу на;bestehen aus|—|складатися з;gehören zu|—|належати до;teilnehmen an|—|брати участь у;sich bewerben um|—|претендувати на;es handelt sich um|—|ідеться про;abhängen von|—|залежати від;sich kümmern um|—|піклуватися про;sich verlassen auf|—|покладатися на;bitten um|—|просити про;zweifeln an|—|сумніватися в;sich entscheiden für|—|обрати`,
"Характер і оцінка":`aufmerksam|—|уважний;gelassen|—|незворушний;ehrgeizig|—|амбітний;großzügig|—|щедрий;geduldig|—|терплячий;hilfsbereit|—|готовий допомогти;misstrauisch|—|недовірливий;rücksichtslos|—|безцеремонний;eingebildet|—|зарозумілий;bescheiden|—|скромний;sinnvoll|—|доцільний;überraschend|—|несподіваний;enttäuschend|—|розчаровуючий;beeindruckend|—|вражаючий;anstrengend|—|виснажливий;lohnend|—|вартий зусиль;umstritten|—|спірний;angemessen|—|доречний;unvermeidlich|—|неминучий;erforderlich|—|необхідний`,
"Сполучники B1":`obwohl|—|хоча;damit|—|щоб (мета);sodass|—|так що;falls|—|у разі якщо;je … desto|—|чим … тим;entweder … oder|—|або … або;weder … noch|—|ні … ні;nicht nur … sondern auch|—|не тільки … а й;deshalb|—|тому;trotzdem|—|попри це;außerdem|—|крім того;allerdings|—|щоправда;jedoch|—|проте;zwar|—|хоч і;einerseits|—|з одного боку;andererseits|—|з іншого боку;beziehungsweise|—|відповідно, або;insbesondere|—|особливо;im Gegensatz zu|—|на відміну від;im Vergleich zu|—|порівняно з`
};
V.B2 = {
"Суспільство й політика":`die Regierung|-en|уряд;die Wahl|-en|вибори;die Partei|-en|партія;das Gesetz|-e|закон;die Verfassung|-en|конституція;der Bürger|-|громадянин;der Abgeordnete|-n|депутат;die Mehrheit|-en|більшість;die Minderheit|-en|меншість;die Demokratie|-n|демократія;die Macht|¨-e|влада;der Einfluss|¨-e|вплив;die Reform|-en|реформа;die Debatte|-n|дебати;der Protest|-e|протест;die Gerechtigkeit|—|справедливість;die Gleichberechtigung|—|рівноправність;die Integration|-en|інтеграція;die Migration|-en|міграція;die Öffentlichkeit|—|громадськість`,
"Економіка":`die Wirtschaft|-en|економіка;die Nachfrage|-n|попит;der Gewinn|-e|прибуток;der Verlust|-e|збиток;die Investition|-en|інвестиція;das Unternehmen|-|підприємство;der Umsatz|¨-e|виторг;die Kosten|—|витрати;die Inflation|-en|інфляція;die Krise|-n|криза;das Wachstum|—|зростання;die Schulden|—|борги;der Verbraucher|-|споживач;die Produktion|-en|виробництво;die Konkurrenz|-en|конкуренція;der Anteil|-e|частка;die Rendite|-n|дохідність;der Haushalt|-e|бюджет;finanzieren|—|фінансувати;sich lohnen|—|бути вигідним`,
"Медіа":`die Nachricht|-en|новина;die Presse|—|преса;der Bericht|-e|репортаж, звіт;die Quelle|-n|джерело;die Schlagzeile|-n|заголовок;der Beitrag|¨-e|допис, внесок;die Sendung|-en|передача;das Interview|-s|інтерв'ю;die Werbung|-en|реклама;das Publikum|—|аудиторія;die Zensur|—|цензура;die Meinungsfreiheit|—|свобода слова;die Fälschung|-en|підробка;glaubwürdig|—|достовірний;sachlich|—|об'єктивний, по суті;berichten|—|повідомляти;veröffentlichen|—|публікувати;recherchieren|—|досліджувати;verbreiten|—|поширювати;manipulieren|—|маніпулювати`,
"Довкілля":`die Umwelt|—|довкілля;der Klimawandel|—|зміна клімату;die Verschmutzung|-en|забруднення;der Abfall|¨-e|відходи;die Energie|-n|енергія;der Verbrauch|—|споживання;die Ressource|-n|ресурс;der Schutz|—|захист;die Art|-en|біологічний вид;das Aussterben|—|вимирання;die Landwirtschaft|—|сільське господарство;die Dürre|-n|посуха;das Hochwasser|-|повінь;die Emission|-en|викид;erneuerbar|—|відновлюваний;nachhaltig|—|сталий;schädlich|—|шкідливий;umweltfreundlich|—|екологічний;recyceln|—|переробляти;vermeiden|—|уникати`,
"Наука":`die Forschung|-en|дослідження;die Wissenschaft|-en|наука;die These|-n|теза;der Beweis|-e|доказ;das Ergebnis|-se|результат;die Studie|-n|наукова праця;die Methode|-n|метод;die Analyse|-n|аналіз;die Statistik|-en|статистика;die Erkenntnis|-se|пізнання, висновок;die Theorie|-n|теорія;die Hypothese|-n|гіпотеза;beobachten|—|спостерігати;messen|—|вимірювати;belegen|—|підтверджувати;widerlegen|—|спростовувати;schlussfolgern|—|робити висновок;zutreffen|—|бути слушним;umfassend|—|всеохопний;empirisch|—|емпіричний`,
"Право":`das Recht|-e|право;die Pflicht|-en|обов'язок;das Gericht|-e|суд;der Anwalt|¨-e|адвокат;das Urteil|-e|вирок, судження;die Strafe|-n|покарання;die Klage|-n|позов;die Haftung|-en|юридична відповідальність;der Verstoß|¨-e|порушення;die Vorschrift|-en|припис;die Auflage|-n|вимога, умова;das Verfahren|-|провадження;zulässig|—|допустимий;verbindlich|—|обов'язковий;verpflichtet|—|зобов'язаний;haften|—|нести відповідальність;verklagen|—|подавати до суду;verstoßen gegen|—|порушувати;gelten|—|бути чинним;in Kraft treten|—|набувати чинності`,
"Абстрактні дієслова":`berücksichtigen|—|враховувати;nachvollziehen|—|простежити логіку;voraussetzen|—|припускати як умову;hinweisen auf|—|вказувати на;beruhen auf|—|ґрунтуватися на;sich auswirken auf|—|впливати на;in Betracht ziehen|—|брати до уваги;zur Verfügung stellen|—|надавати;eine Rolle spielen|—|відігравати роль;in Frage stellen|—|ставити під сумнів;zum Ausdruck bringen|—|виражати;Rücksicht nehmen auf|—|зважати на;Wert legen auf|—|надавати значення;eine Entscheidung treffen|—|ухвалювати рішення;Kritik üben|—|критикувати;Maßnahmen ergreifen|—|вживати заходів;zur Folge haben|—|мати наслідком;im Vordergrund stehen|—|бути на першому плані;sich erweisen als|—|виявитися чимось;erfordern|—|вимагати`,
"Оцінка й ступінь":`erheblich|—|значний;gering|—|незначний;umfangreich|—|обширний;zutreffend|—|слушний;fragwürdig|—|сумнівний;maßgeblich|—|визначальний;ausschlaggebend|—|вирішальний;nachweislich|—|доведено;vermeintlich|—|нібито;offensichtlich|—|очевидний;grundsätzlich|—|принципово;weitgehend|—|значною мірою;vorläufig|—|попередній;endgültig|—|остаточний;zunehmend|—|дедалі більший;rückläufig|—|спадний;ausgeprägt|—|виразний;unerlässlich|—|конче потрібний;bedenklich|—|тривожний;vielfältig|—|різноманітний`,
"Формальні звороти":`hinsichtlich|—|щодо;bezüglich|—|стосовно;aufgrund|—|на підставі;infolge|—|внаслідок;angesichts|—|з огляду на;im Hinblick auf|—|з огляду на;im Rahmen|—|у рамках;im Zuge|—|у ході;mit Ausnahme von|—|за винятком;im Wesentlichen|—|по суті;in erster Linie|—|насамперед;unter Umständen|—|за певних обставин;in der Regel|—|як правило;im Durchschnitt|—|у середньому;darüber hinaus|—|понад те;somit|—|отже;folglich|—|відтак;demnach|—|згідно з цим;letztlich|—|зрештою;zum einen … zum anderen|—|з одного … з іншого`,
"Konnektoren":`zumal|—|тим паче що;sofern|—|за умови що;indem|—|тим, що (спосіб);während|—|тоді як;wohingegen|—|натомість;sobald|—|щойно;solange|—|поки;bevor|—|перш ніж;nachdem|—|після того як;seitdem|—|відтоді як;es sei denn|—|хіба що;statt zu|—|замість того щоб;ohne zu|—|не роблячи чогось;um zu|—|щоб;anstatt dass|—|замість того щоб;insofern|—|остільки;dementsprechend|—|відповідно;gleichermaßen|—|однаковою мірою;vorausgesetzt, dass|—|за умови, що;abgesehen von|—|окрім`
};
V.C1 = {
"Академічна лексика":`die Erörterung|-en|розгляд, обговорення;der Ansatz|¨-e|підхід;die Perspektive|-n|перспектива;das Phänomen|-e|явище;die Wechselwirkung|-en|взаємодія;die Tragweite|—|масштаб наслідків;die Ambivalenz|-en|амбівалентність;der Diskurs|-e|дискурс;die Prämisse|-n|засновок;die Schlussfolgerung|-en|висновок;der Widerspruch|¨-e|суперечність;die Differenzierung|-en|розрізнення;die Relevanz|—|значущість;die Plausibilität|—|правдоподібність;die Einschränkung|-en|застереження;die Verallgemeinerung|-en|узагальнення;zugrunde liegen|—|лежати в основі;sich abzeichnen|—|вимальовуватися;hervorheben|—|наголошувати;abwägen|—|зважувати`,
"Функціональні звороти":`in Anspruch nehmen|—|скористатися, забирати час;zur Sprache bringen|—|порушити тему;Abstand nehmen von|—|відмовитися від;in Kauf nehmen|—|змиритися з;zur Debatte stehen|—|бути предметом обговорення;außer Acht lassen|—|лишити поза увагою;in Erwägung ziehen|—|розглядати як варіант;Rechnung tragen|—|враховувати;unter Beweis stellen|—|довести на ділі;zum Tragen kommen|—|проявитися;Anklang finden|—|знайти відгук;ins Gewicht fallen|—|мати вагу;in Aussicht stellen|—|обіцяти;sich in Grenzen halten|—|бути помірним;auf dem Spiel stehen|—|бути під загрозою;den Ausschlag geben|—|стати вирішальним;ins Auge fassen|—|намітити;zur Verantwortung ziehen|—|притягнути до відповідальності;Stellung nehmen zu|—|висловити позицію щодо;in Verruf geraten|—|здобути погану славу`,
"Modalpartikeln":`doch|—|же (наполягання);ja|—|ж (спільне знання);mal|—|-но (пом'якшення);eben|—|саме так, нічого не вдієш;halt|—|ну просто;wohl|—|мабуть;denn|—|же (у питанні);etwa|—|невже, приблизно;schon|—|таки;ruhig|—|спокійно можеш;bloß|—|тільки (застереження);nur|—|лише;eigentlich|—|власне кажучи;überhaupt|—|взагалі;immerhin|—|принаймні;sowieso|—|все одно;ohnehin|—|і без того;gewissermaßen|—|певною мірою;freilich|—|звісно, щоправда;durchaus|—|цілком`,
"Ідіоми":`die Daumen drücken|—|тримати кулаки;ins kalte Wasser springen|—|кинутися у вир;den Nagel auf den Kopf treffen|—|влучити в яблучко;die Katze im Sack kaufen|—|купити кота в мішку;mit dem Feuer spielen|—|гратися з вогнем;die Zähne zusammenbeißen|—|зціпити зуби;über den Tellerrand schauen|—|дивитися ширше;das Rad neu erfinden|—|винаходити велосипед;auf großem Fuß leben|—|жити на широку ногу;den Faden verlieren|—|згубити думку;ins Fettnäpfchen treten|—|сісти в калюжу;Öl ins Feuer gießen|—|підливати оливи у вогонь;aus dem Ärmel schütteln|—|зробити без зусиль;jemandem die Stange halten|—|заступатися;die Flinte ins Korn werfen|—|опустити руки;Schwein haben|—|мати везіння;auf dem Holzweg sein|—|помилятися;das Handtuch werfen|—|здатися;Hals über Kopf|—|стрімголов;unter vier Augen|—|віч-на-віч`,
"Книжна лексика":`gleichwohl|—|попри це;mithin|—|отже;zumindest|—|принаймні;keineswegs|—|аж ніяк;mitnichten|—|аж ніяк (висок.);schlechthin|—|як такий;vollends|—|остаточно;zusehends|—|дедалі помітніше;unlängst|—|нещодавно;seinerzeit|—|свого часу;hierzulande|—|у нас у країні;dergestalt|—|таким чином;nichtsdestotrotz|—|попри все;beiläufig|—|мимохідь;vorbehaltlich|—|за умови;namentlich|—|зокрема;vornehmlich|—|переважно;weitestgehend|—|максимально;schlichtweg|—|просто-таки;fortan|—|відтепер`,
"Нюанси синонімів":`erwidern|—|заперечити у відповідь;entgegnen|—|заперечити;behaupten|—|стверджувати;einräumen|—|визнати (поступка);bestreiten|—|заперечувати;beteuern|—|запевняти;andeuten|—|натякати;unterstellen|—|приписувати (негатив);verharmlosen|—|применшувати;zuspitzen|—|загострювати;relativieren|—|релятивізувати;untermauern|—|підкріпити;hinterfragen|—|ставити під питання;nahelegen|—|наштовхувати на думку;schildern|—|змальовувати;erläutern|—|роз'яснювати;darlegen|—|викладати;ausführen|—|розгортати думку;zusammenfassen|—|підсумовувати;einwenden|—|заперечити (аргумент)`,
"Психологія й філософія":`das Bewusstsein|—|свідомість;die Wahrnehmung|-en|сприйняття;das Unterbewusstsein|—|підсвідомість;die Vernunft|—|розум;die Willensfreiheit|—|свобода волі;die Sinnfrage|-n|питання сенсу;das Dasein|—|буття;die Sehnsucht|¨-e|туга, прагнення;die Verzweiflung|—|відчай;die Gelassenheit|—|незворушність;die Zuversicht|—|упевненість у майбутньому;das Vorurteil|-e|упередження;die Selbstverwirklichung|—|самореалізація;die Entfremdung|—|відчуження;das Gewissen|-|сумління;die Reue|—|каяття;die Demut|—|смиренність;der Zweifel|-|сумнів;die Absurdität|-en|абсурдність;das Streben|—|прагнення`,
"Адміністративна мова":`der Sachverhalt|-e|обставини справи;die Zuständigkeit|-en|компетенція;der Ermessensspielraum|¨-e|простір розсуду;der Bescheid|-e|адміністративне рішення;die Rechtsgrundlage|-n|правова підстава;die Beweislast|—|тягар доказування;der Verzug|—|прострочення;die Kündigungsfrist|-en|строк розірвання;die Bevollmächtigung|-en|уповноваження;das Einvernehmen|—|порозуміння;die Zustimmung|-en|згода;Widerspruch einlegen|—|подати заперечення;eine Frist versäumen|—|пропустити строк;unverzüglich|—|невідкладно;vorbehalten|—|застережений;rechtskräftig|—|такий, що набув чинності;einvernehmlich|—|за взаємною згодою;zuwiderhandeln|—|діяти всупереч;beglaubigen|—|засвідчувати;erlassen|—|видавати (акт)`,
"Розмовна німецька":`Quatsch|—|дурня;krass|—|жесть, крутезно;echt jetzt?|—|серйозно?;na klar|—|звісно;keine Ahnung|—|поняття не маю;das nervt|—|це дратує;es hat geklappt|—|вийшло;ich bin fix und fertig|—|я вимотана;das geht mir auf die Nerven|—|це діє мені на нерви;mir reicht's|—|з мене досить;lass mal|—|облиш;kein Ding|—|не проблема;das kommt drauf an|—|залежить;auf jeden Fall|—|у будь-якому разі;im Ernst|—|серйозно;mach's gut|—|бувай;alles klar|—|все ясно;das war knapp|—|ледь встигли;ganz schön|—|доволі;so gesehen|—|якщо так подивитись`,
"Літературна лексика":`die Wehmut|—|меланхолія;das Fernweh|—|туга за далекими краями;die Geborgenheit|—|захищеність, затишок;der Zeitgeist|—|дух часу;die Zerrissenheit|—|внутрішня роздертість;die Vergänglichkeit|—|минущість;die Anmut|—|грація;der Abgrund|¨-e|прірва;die Stille|—|тиша;das Schicksal|-e|доля;die Ahnung|-en|передчуття;der Trost|—|розрада;die Ernüchterung|—|витвереження;das Unbehagen|—|незатишок;die Zuflucht|¨-e|прихисток;der Widerhall|—|відлуння;die Wucht|—|потуга;schwelgen|—|поринати, розкошувати;verweilen|—|затримуватися;erahnen|—|здогадуватися`
};
Object.assign(V.A1,{
"Кольори й форми":`rot|—|червоний;blau|—|синій;grün|—|зелений;gelb|—|жовтий;schwarz|—|чорний;weiß|—|білий;grau|—|сірий;braun|—|коричневий;orange|—|помаранчевий;rosa|—|рожевий;bunt|—|барвистий;dunkel|—|темний;hell|—|світлий;rund|—|круглий;eckig|—|кутастий;die Farbe|-n|колір;die Form|-en|форма;breit|—|широкий;schmal|—|вузький;dick|—|товстий`,
"Числівники":`eins|—|один;zwei|—|два;drei|—|три;vier|—|чотири;fünf|—|п'ять;sechs|—|шість;sieben|—|сім;acht|—|вісім;neun|—|дев'ять;zehn|—|десять;elf|—|одинадцять;zwölf|—|дванадцять;zwanzig|—|двадцять;hundert|—|сто;tausend|—|тисяча;die Hälfte|-n|половина;das Stück|-e|штука;das Paar|-e|пара;ungefähr|—|приблизно;genau|—|точно`,
"Школа":`die Klasse|-n|клас;der Lehrer|-|вчитель;die Lehrerin|-nen|вчителька;der Schüler|-|учень;das Heft|-e|зошит;der Stift|-e|ручка;das Papier|-e|папір;die Tafel|-n|дошка;die Hausaufgabe|-n|домашнє завдання;das Fach|¨-er|навчальний предмет;die Sprache|-n|мова;das Wort|¨-er|слово;der Satz|¨-e|речення;die Frage|-n|питання;die Antwort|-en|відповідь;der Fehler|-|помилка;die Übung|-en|вправа;üben|—|вправлятися;fragen|—|питати;antworten|—|відповідати`,
"Тварини":`der Hund|-e|собака;die Katze|-n|кішка;das Pferd|-e|кінь;die Kuh|¨-e|корова;das Schwein|-e|свиня;der Vogel|¨|птах;die Maus|¨-e|миша;der Bär|-en|ведмідь;der Wolf|¨-e|вовк;der Fuchs|¨-e|лис;das Schaf|-e|вівця;die Ziege|-n|коза;das Huhn|¨-er|курка;die Ente|-n|качка;der Hase|-n|заєць;die Biene|-n|бджола;die Fliege|-n|муха;der Käfer|-|жук;das Insekt|-en|комаха;der Zoo|-s|зоопарк`,
"Дії щодня":`aufstehen|—|вставати;sich waschen|—|митися;sich anziehen|—|вдягатися;frühstücken|—|снідати;putzen|—|чистити;kochen|—|готувати їжу;waschen|—|прати;aufräumen|—|прибирати;einkaufen|—|робити покупки;spazieren gehen|—|гуляти;fernsehen|—|дивитися телевізор;telefonieren|—|телефонувати;spielen|—|грати;singen|—|співати;tanzen|—|танцювати;laufen|—|бігти;schwimmen|—|плавати;sitzen|—|сидіти;stehen|—|стояти;liegen|—|лежати`,
"Місце й напрямок":`links|—|ліворуч;rechts|—|праворуч;geradeaus|—|прямо;oben|—|вгорі;unten|—|внизу;vorne|—|спереду;hinten|—|ззаду;drinnen|—|всередині;draußen|—|надворі;überall|—|скрізь;nirgends|—|ніде;weit|—|далеко;nah|—|близько;die Ecke|-n|ріг;die Mitte|-n|середина;der Weg|-e|шлях;die Seite|-n|бік, сторінка;das Ende|-n|кінець;der Anfang|¨-e|початок;zurück|—|назад`,
"Ввічливість":`danke|—|дякую;bitte|—|будь ласка;Entschuldigung|-en|перепрошую;hallo|—|привіт;tschüss|—|бувай;guten Morgen|—|доброго ранку;guten Tag|—|добрий день;gute Nacht|—|надобраніч;auf Wiedersehen|—|до побачення;wie geht's?|—|як справи?;gern geschehen|—|прошу (у відповідь);herzlich willkommen|—|ласкаво просимо;viel Glück|—|щасти;alles Gute|—|усього доброго;kein Problem|—|немає проблем;natürlich|—|звісно;vielleicht|—|можливо;leider|—|на жаль;hoffentlich|—|сподіваюся;stimmt|—|так, правильно`,
"Професії":`die Ärztin|-nen|лікарка;der Ingenieur|-e|інженер;der Koch|¨-e|кухар;der Kellner|-|офіціант;der Fahrer|-|водій;der Bäcker|-|пекар;der Friseur|-e|перукар;der Student|-en|студент;die Studentin|-nen|студентка;der Künstler|-|митець;der Musiker|-|музикант;der Sportler|-|спортсмен;der Journalist|-en|журналіст;der Programmierer|-|програміст;die Krankenschwester|-n|медсестра;der Landwirt|-e|фермер;der Handwerker|-|ремісник;die Sekretärin|-nen|секретарка;der Rentner|-|пенсіонер;der Polizist|-en|поліціянт`,
"Кухня й посуд":`der Teller|-|тарілка;die Tasse|-n|чашка;das Glas|¨-er|склянка;die Gabel|-n|виделка;das Messer|-|ніж;der Topf|¨-e|каструля;die Pfanne|-n|сковорода;der Herd|-e|плита;der Kühlschrank|¨-e|холодильник;der Ofen|¨|духовка;die Flasche|-n|пляшка;die Dose|-n|бляшанка;die Serviette|-n|серветка;das Handtuch|¨-er|рушник;die Seife|-n|мило;der Schwamm|¨-e|губка;das Öl|-e|олія;der Essig|-e|оцет;das Mehl|-e|борошно;die Nudeln|—|локшина`,
"Дні й місяці":`Montag|—|понеділок;Dienstag|—|вівторок;Mittwoch|—|середа;Donnerstag|—|четвер;Freitag|—|п'ятниця;Samstag|—|субота;Sonntag|—|неділя;Januar|—|січень;Februar|—|лютий;März|—|березень;April|—|квітень;Mai|—|травень;Juni|—|червень;Juli|—|липень;August|—|серпень;September|—|вересень;Oktober|—|жовтень;November|—|листопад;Dezember|—|грудень;das Wochenende|-n|вихідні`});

Object.assign(V.A2,{
"Спорт і дозвілля":`der Sport|—|спорт;das Spiel|-e|гра;die Mannschaft|-en|команда;der Verein|-e|клуб, товариство;das Training|-s|тренування;der Wettkampf|¨-e|змагання;der Sieg|-e|перемога;die Niederlage|-n|поразка;das Hobby|-s|хобі;die Freizeit|—|дозвілля;wandern|—|мандрувати пішки;Rad fahren|—|їздити на велосипеді;trainieren|—|тренуватися;gewinnen|—|вигравати;sich anstrengen|—|напружуватися;das Fitnessstudio|-s|спортзал;der Schiedsrichter|-|суддя;die Mitgliedschaft|-en|членство;fit|—|у формі;sportlich|—|спортивний`,
"Транспорт":`die Straßenbahn|-en|трамвай;die U-Bahn|-en|метро;das Flugzeug|-e|літак;das Schiff|-e|корабель;das Taxi|-s|таксі;der Führerschein|-e|водійські права;die Tankstelle|-n|заправка;das Benzin|—|бензин;der Stau|-s|затор;die Ampel|-n|світлофор;die Kreuzung|-en|перехрестя;der Unfall|¨-e|аварія;die Geschwindigkeit|-en|швидкість;parken|—|паркуватися;bremsen|—|гальмувати;überholen|—|обганяти;abbiegen|—|повертати;die Fahrkarte|-n|проїзний квиток;der Fahrgast|¨-e|пасажир;der Bahnsteig|-e|перон`,
"Техніка вдома":`der Fernseher|-|телевізор;der Computer|-|комп'ютер;das Handy|-s|мобільний;der Drucker|-|принтер;die Waschmaschine|-n|пральна машина;die Spülmaschine|-n|посудомийка;der Staubsauger|-|пилосос;die Mikrowelle|-n|мікрохвильовка;der Wecker|-|будильник;die Steckdose|-n|розетка;das Kabel|-|кабель;der Akku|-s|акумулятор;das Ladegerät|-e|зарядний пристрій;anschalten|—|вмикати;ausschalten|—|вимикати;funktionieren|—|працювати (про техніку);kaputt|—|зламаний;reparieren|—|ремонтувати;die Fernbedienung|-en|пульт;die Batterie|-n|батарейка`,
"Послуги в місті":`die Reinigung|-en|хімчистка;der Friseursalon|-s|перукарня;die Bibliothek|-en|бібліотека;das Rathaus|¨-er|ратуша;das Museum|Museen|музей;das Theater|-|театр;das Kino|-s|кінотеатр;das Schwimmbad|¨-er|басейн;der Supermarkt|¨-e|супермаркет;die Bäckerei|-en|пекарня;die Metzgerei|-en|м'ясна крамниця;das Restaurant|-s|ресторан;das Café|-s|кав'ярня;die Kneipe|-n|пивна;der Kiosk|-e|кіоск;die Polizei|—|поліція;die Feuerwehr|-en|пожежна служба;der Notruf|-e|виклик екстрених служб;die Öffnungszeiten|—|години роботи;geschlossen|—|зачинено`,
"Дім: дії й частини":`mieten|—|орендувати;vermieten|—|здавати в оренду;umziehen|—|переїжджати;klingeln|—|дзвонити у двері;öffnen|—|відчиняти;schließen|—|зачиняти;heizen|—|опалювати;lüften|—|провітрювати;bauen|—|будувати;streichen|—|фарбувати;hängen|—|вішати;stellen|—|ставити;legen|—|класти;der Aufzug|¨-e|ліфт;der Keller|-|підвал;der Balkon|-e|балкон;das Dach|¨-er|дах;die Decke|-n|стеля;der Flur|-e|коридор;das Erdgeschoss|-e|перший поверх`,
"Характер":`nett|—|милий;lustig|—|веселий;traurig|—|сумний;streng|—|суворий;klug|—|розумний;dumm|—|дурний;mutig|—|сміливий;schüchtern|—|сором'язливий;sympathisch|—|симпатичний;langweilig|—|нудний;interessant|—|цікавий;aufgeregt|—|схвильований;glücklich|—|щасливий;unglücklich|—|нещасливий;ernst|—|серйозний;offen|—|відкритий;egoistisch|—|егоїстичний;sparsam|—|ощадливий;großzügig|—|щедрий;empfindlich|—|вразливий`,
"Дієслова A2 ч.2":`ändern|—|змінювати;benutzen|—|користуватися;besuchen|—|відвідувати;bedeuten|—|означати;gehören|—|належати;passieren|—|траплятися;passen|—|пасувати;schenken|—|дарувати;sich setzen|—|сідати;zeigen|—|показувати;bestellen|—|замовляти;buchstabieren|—|вимовляти по літерах;wiegen|—|важити;mitbringen|—|приносити з собою;vorstellen|—|представляти;sich vorstellen|—|уявляти;sich verabreden|—|домовлятися про зустріч;absagen|—|скасовувати;verschieben|—|переносити;stattfinden|—|відбуватися`,
"Ступінь і оцінка":`ziemlich|—|доволі;besonders|—|особливо;wirklich|—|справді;fast|—|майже;kaum|—|заледве;völlig|—|цілком;total|—|повністю;etwas|—|трохи;genug|—|достатньо;zu viel|—|занадто багато;mindestens|—|щонайменше;höchstens|—|щонайбільше;überhaupt nicht|—|зовсім ні;auf keinen Fall|—|у жодному разі;unbedingt|—|обов'язково;wahrscheinlich|—|імовірно;sicherlich|—|напевно;eventuell|—|можливо;ausgezeichnet|—|відмінно;furchtbar|—|жахливо`,
"Свята й традиції":`das Fest|-e|свято;der Geburtstag|-e|день народження;Weihnachten|—|Різдво;Ostern|—|Великдень;Silvester|—|новорічна ніч;das Geschenk|-e|подарунок;die Einladung|-en|запрошення;der Gast|¨-e|гість;gratulieren|—|вітати;feiern|—|святкувати;einladen|—|запрошувати;der Brauch|¨-e|звичай;die Kerze|-n|свічка;der Kuchen|-|пиріг;die Torte|-n|торт;das Lied|-er|пісня;der Tanz|¨-e|танець;das Feuerwerk|-e|феєрверк;die Tradition|-en|традиція;der Feiertag|-e|святковий день`,
"Кількість і порівняння":`mehr|—|більше;weniger|—|менше;gleich|—|однаково, зараз;dasselbe|—|те саме;anders|—|інакше;jeder|—|кожен;alle|—|усі;einige|—|деякі;mehrere|—|кілька;niemand|—|ніхто;jemand|—|хтось;nichts|—|нічого;alles|—|усе;beide|—|обидва;die Menge|-n|кількість;die Anzahl|-en|число, кількість;der Rest|-e|решта;der Teil|-e|частина;insgesamt|—|загалом;durchschnittlich|—|у середньому`});

Object.assign(V.B1,{
"Робота: процеси":`der Ablauf|¨-e|перебіг;der Prozess|-e|процес;die Planung|-en|планування;die Umsetzung|-en|впровадження;der Vorschlag|¨-e|пропозиція;die Rückmeldung|-en|зворотний зв'язок;die Verbesserung|-en|покращення;die Verzögerung|-en|затримка;der Aufwand|—|витрати зусиль;der Ertrag|¨-e|дохід, віддача;die Effizienz|—|ефективність;organisieren|—|організовувати;koordinieren|—|координувати;delegieren|—|делегувати;umsetzen|—|втілювати;überprüfen|—|перевіряти;abstimmen|—|узгоджувати;vereinbaren|—|домовлятися;beauftragen|—|доручати;die Zwischenbilanz|-en|проміжний підсумок`,
"Фінанси":`das Einkommen|-|дохід;die Ausgabe|-n|видаток;die Einnahme|-n|надходження;das Vermögen|-|статок;die Rente|-n|пенсія;der Kredit|-e|кредит;die Zinsen|—|відсотки;die Rate|-n|платіж частинами;das Budget|-s|бюджет;die Gebühr|-en|збір, комісія;die Rücklage|-n|резерв;die Steuererklärung|-en|податкова декларація;sich leisten|—|дозволити собі;anlegen|—|вкладати кошти;abheben|—|знімати гроші;einzahlen|—|вносити гроші;kalkulieren|—|розраховувати;schulden|—|бути винним;finanziell|—|фінансовий;die Rechnung begleichen|—|погасити рахунок`,
"Культура й мистецтво":`die Kunst|¨-e|мистецтво;das Gemälde|-|картина;die Ausstellung|-en|виставка;das Kunstwerk|-e|витвір мистецтва;die Aufführung|-en|вистава;die Bühne|-n|сцена;der Roman|-e|роман;das Gedicht|-e|вірш;der Autor|-en|автор;der Regisseur|-e|режисер;die Handlung|-en|сюжет;die Figur|-en|персонаж;das Werk|-e|твір;die Kritik|-en|критика;die Vorstellung|-en|вистава, уявлення;inszenieren|—|ставити виставу;darstellen|—|зображати;veranstalten|—|влаштовувати;kulturell|—|культурний;künstlerisch|—|мистецький`,
"Дієслова B1 ч.2":`erwarten|—|очікувати;vermuten|—|припускати;behalten|—|залишати собі;erlauben|—|дозволяти;verbieten|—|забороняти;verlangen|—|вимагати;fordern|—|вимагати наполегливо;fördern|—|сприяти;verhindern|—|запобігати;ermöglichen|—|уможливлювати;erledigen|—|залагоджувати;bewältigen|—|долати;erreichen|—|досягати;verpassen|—|проґавити;betreffen|—|стосуватися;auffallen|—|впадати в око;gelingen|—|вдаватися;misslingen|—|не вдаватися;ausreichen|—|бути достатнім;entsprechen|—|відповідати`,
"Іменники дії":`die Veränderung|-en|зміна;die Entstehung|-en|виникнення;die Erhöhung|-en|підвищення;die Senkung|-en|зниження;die Verteilung|-en|розподіл;die Einführung|-en|запровадження;die Abschaffung|-en|скасування;die Erweiterung|-en|розширення;die Beschränkung|-en|обмеження;die Durchführung|-en|проведення;die Bewertung|-en|оцінювання;die Beobachtung|-en|спостереження;die Erklärung|-en|пояснення;die Feststellung|-en|констатація;die Wiederholung|-en|повторення;die Zunahme|-n|приріст;die Abnahme|-n|спад;die Ausbreitung|-en|поширення;die Umstellung|-en|перехід;die Gestaltung|-en|оформлення`,
"Стан і властивість":`zuständig|—|відповідальний за;bereit|—|готовий;fähig|—|здатний;abhängig|—|залежний;unabhängig|—|незалежний;verfügbar|—|доступний;nützlich|—|корисний;notwendig|—|необхідний;üblich|—|звичний;selbstverständlich|—|само собою зрозуміло;auffällig|—|помітний;deutlich|—|виразний;unklar|—|нечіткий;eindeutig|—|однозначний;vorsichtig|—|обережний;gründlich|—|ґрунтовний;flexibel|—|гнучкий;stabil|—|стабільний;knapp|—|обмежений;wesentlich|—|суттєвий`,
"Спілкування":`das Gespräch|-e|розмова;die Auskunft|¨-e|довідка;die Mitteilung|-en|повідомлення;die Ankündigung|-en|оголошення;der Hinweis|-e|вказівка;die Bemerkung|-en|зауваження;der Ratschlag|¨-e|порада;die Zusage|-n|згода, обіцянка;die Absage|-n|відмова;das Versprechen|-|обіцянка;mitteilen|—|повідомляти;erwähnen|—|згадувати;betonen|—|наголошувати;wiedergeben|—|переказувати;sich äußern|—|висловлюватися;schweigen|—|мовчати;unterbrechen|—|перебивати;zuhören|—|слухати;nachfragen|—|перепитувати;klarstellen|—|прояснити`,
"Час і зміни":`die Vergangenheit|—|минуле;die Gegenwart|—|теперішнє;die Zukunft|—|майбутнє;die Epoche|-n|епоха;der Zeitraum|¨-e|проміжок часу;der Zeitpunkt|-e|момент;die Dauer|—|тривалість;der Verlauf|¨-e|перебіг;der Rhythmus|Rhythmen|ритм;die Phase|-n|фаза;dauern|—|тривати;verlaufen|—|проходити;sich verändern|—|змінюватися;sich entwickeln|—|розвиватися;zunehmen|—|зростати;abnehmen|—|спадати;bleiben|—|лишатися;verschwinden|—|зникати;entstehen|—|виникати;wiederkehren|—|повертатися`,
"Бюрократія":`das Amt|¨-er|відомство;die Sachbearbeiterin|-nen|референтка;der Schalter|-|віконце обслуговування;die Warteschlange|-n|черга;der Stempel|-|печатка;die Kopie|-n|копія;die Vollmacht|-en|довіреність;die Aufenthaltserlaubnis|-se|дозвіл на перебування;die Arbeitserlaubnis|-se|дозвіл на роботу;die Krankenkasse|-n|лікарняна каса;die Sozialversicherung|-en|соцстрахування;die Steuernummer|-n|податковий номер;einen Termin vereinbaren|—|призначити зустріч;einreichen|—|подавати документи;bearbeiten|—|опрацьовувати;genehmigen|—|схвалювати;verweigern|—|відмовляти;nachweisen|—|доводити;vorlegen|—|подати на розгляд;zuständig sein|—|бути компетентним`,
"Споживання":`die Verpackung|-en|упаковка;das Etikett|-en|етикетка;die Haltbarkeit|—|термін придатності;die Zutat|-en|інгредієнт;die Portion|-en|порція;die Mahlzeit|-en|прийом їжі;die Ernährungsweise|-n|спосіб харчування;der Geschmack|¨-e|смак;die Qualität|-en|якість;die Auswahl|-en|вибір, асортимент;die Garantie|-n|гарантія;der Umtausch|—|обмін товару;die Beschwerde|-n|скарга;die Empfehlung|-en|рекомендація;probieren|—|куштувати;verbrauchen|—|споживати;wegwerfen|—|викидати;aufbewahren|—|зберігати;haltbar|—|тривкий;liefern|—|постачати`});

Object.assign(V.B2,{
"Політика ч.2":`die Koalition|-en|коаліція;die Opposition|-en|опозиція;der Kanzler|-|канцлер;das Parlament|-e|парламент;die Wahlbeteiligung|-en|явка на виборах;der Wahlkampf|¨-e|виборча кампанія;die Amtszeit|-en|термін повноважень;die Souveränität|—|суверенітет;das Bündnis|-se|союз;die Sanktion|-en|санкція;die Diplomatie|—|дипломатія;die Verhandlung|-en|переговори;der Konsens|-e|консенсус;die Spaltung|-en|розкол;die Propaganda|—|пропаганда;der Populismus|—|популізм;die Zivilgesellschaft|-en|громадянське суспільство;regieren|—|правити;verhandeln|—|вести переговори;der Staatshaushalt|-e|державний бюджет`,
"Освіта й наука ч.2":`die Fakultät|-en|факультет;der Dozent|-en|викладач;die Dissertation|-en|дисертація;das Stipendium|Stipendien|стипендія;die Fachrichtung|-en|напрям;die Lehre|-n|вчення;der Lehrplan|¨-e|навчальний план;die Kompetenz|-en|компетенція;die Qualifikation|-en|кваліфікація;das Fachwissen|—|фахові знання;die Fortbildung|-en|післядипломне навчання;der Nachwuchs|—|молода зміна;die Begabung|-en|обдарування;die Förderung|-en|сприяння;akademisch|—|академічний;interdisziplinär|—|міждисциплінарний;theoretisch|—|теоретичний;praktisch|—|практичний;vermitteln|—|передавати знання;sich aneignen|—|засвоювати`,
"Соціальні теми":`die Armut|—|бідність;der Wohlstand|—|добробут;die Ungleichheit|-en|нерівність;die Chancengleichheit|—|рівність можливостей;die Diskriminierung|-en|дискримінація;die Ausgrenzung|-en|маргіналізація;die Solidarität|—|солідарність;der Zusammenhalt|—|згуртованість;die Generation|-en|покоління;die Alterung|—|старіння населення;die Bevölkerung|-en|населення;die Geburtenrate|-n|народжуваність;der Wohnraum|¨-e|житловий фонд;die Obdachlosigkeit|—|бездомність;die Kriminalität|—|злочинність;die Prävention|-en|запобігання;die Fürsorge|—|опіка;benachteiligt|—|знедолений;gesellschaftlich|—|суспільний;der Missstand|¨-e|негаразд`,
"Бізнес":`die Strategie|-n|стратегія;das Konzept|-e|концепція;die Zielgruppe|-n|цільова аудиторія;der Marktanteil|-e|частка ринку;die Marke|-n|бренд;der Vertrieb|-e|збут;die Beschaffung|-en|закупівля;die Logistik|—|логістика;die Rentabilität|—|рентабельність;die Fusion|-en|злиття;die Übernahme|-n|поглинання;der Aktionär|-e|акціонер;die Aktie|-n|акція;der Vorstand|¨-e|правління;die Bilanz|-en|баланс;der Jahresabschluss|¨-e|річний звіт;expandieren|—|розширюватися;optimieren|—|оптимізувати;skalieren|—|масштабувати;wirtschaftlich|—|економічний`,
"Аргументація":`das Argument|-e|аргумент;die Begründung|-en|обґрунтування;der Einwand|¨-e|заперечення;die Gegenposition|-en|протилежна позиція;die Abwägung|-en|зважування;der Standpunkt|-e|погляд;die Stellungnahme|-n|заява, позиція;die Behauptung|-en|твердження;der Beleg|-e|підтвердження;das Beispiel|-e|приклад;die Einschätzung|-en|оцінка ситуації;das Fazit|-s|підсумок;begründen|—|обґрунтовувати;widersprechen|—|суперечити;entkräften|—|спростувати;veranschaulichen|—|унаочнити;gegenüberstellen|—|зіставляти;hervorbringen|—|породжувати;plausibel|—|правдоподібний;stichhaltig|—|переконливий`,
"Дієслова B2 ч.2":`bewirken|—|спричиняти;verursachen|—|викликати;beitragen zu|—|сприяти чомусь;beeinträchtigen|—|погіршувати;begünstigen|—|сприяти;eindämmen|—|стримувати;bekämpfen|—|боротися з;gewährleisten|—|забезпечувати;sicherstellen|—|гарантувати;überwiegen|—|переважати;abweichen|—|відхилятися;übertreffen|—|перевершувати;nachlassen|—|слабшати;anhalten|—|тривати;aufweisen|—|мати ознаку;umfassen|—|охоплювати;betragen|—|становити кількість;sich belaufen auf|—|сягати суми;ausmachen|—|складати;zurückführen auf|—|зводити до причини`,
"Прикметники B2 ч.2":`langfristig|—|довгостроковий;kurzfristig|—|короткостроковий;nachvollziehbar|—|обґрунтований;unzureichend|—|недостатній;übermäßig|—|надмірний;beträchtlich|—|значний;vernachlässigbar|—|незначний;entscheidend|—|вирішальний;wechselseitig|—|взаємний;einheitlich|—|однорідний;gezielt|—|цілеспрямований;systematisch|—|систематичний;drastisch|—|різкий;moderat|—|поміркований;anfällig|—|вразливий;robust|—|стійкий;transparent|—|прозорий;verlässlich|—|надійний;strittig|—|спірний;wegweisend|—|знаковий`,
"Процеси й структури":`der Mechanismus|Mechanismen|механізм;die Struktur|-en|структура;das System|-e|система;der Rahmen|-|рамки;das Verhältnis|-se|співвідношення;die Dimension|-en|вимір;die Ebene|-n|рівень;der Bereich|-e|сфера;das Ausmaß|-e|масштаб;die Tendenz|-en|тенденція;die Dynamik|-en|динаміка;die Konstellation|-en|розстановка;der Faktor|-en|фактор;der Indikator|-en|показник;die Variable|-n|змінна;die Korrelation|-en|кореляція;die Ursache|-n|причина;die Auswirkung|-en|наслідок;die Wechselbeziehung|-en|взаємозв'язок;die Rückkopplung|-en|зворотний зв'язок`,
"Медицина й технології":`die Impfung|-en|щеплення;die Epidemie|-n|епідемія;die Therapie|-n|терапія;der Eingriff|-e|втручання;die Genetik|—|генетика;die Zelle|-n|клітина;das Immunsystem|-e|імунна система;die Diagnostik|—|діагностика;die Digitalisierung|—|цифровізація;der Algorithmus|Algorithmen|алгоритм;die Automatisierung|—|автоматизація;die Datenbank|-en|база даних;die Verschlüsselung|-en|шифрування;der Datenschutz|—|захист даних;die Schnittstelle|-n|інтерфейс;die Innovation|-en|інновація;das Patent|-e|патент;die Anwendungsmöglichkeit|-en|можливість застосування;implementieren|—|впроваджувати;revolutionieren|—|революціонізувати`,
"Прислівники B2":`vermutlich|—|імовірно;anscheinend|—|схоже, що;scheinbar|—|позірно;bekanntlich|—|як відомо;erfahrungsgemäß|—|за досвідом;erwartungsgemäß|—|як і очікувалося;überraschenderweise|—|на диво;bedauerlicherweise|—|на жаль;glücklicherweise|—|на щастя;interessanterweise|—|цікаво, що;üblicherweise|—|зазвичай;keinesfalls|—|у жодному разі;jedenfalls|—|у всякому разі;weitaus|—|набагато;nämlich|—|а саме;gegebenenfalls|—|за потреби;daraufhin|—|після чого;infolgedessen|—|унаслідок цього;stattdessen|—|натомість;hierbei|—|при цьому`});

Object.assign(V.C1,{
"Філософія й теорія":`die Erkenntnistheorie|-n|теорія пізнання;die Ontologie|-n|онтологія;die Ethik|—|етика;die Ästhetik|—|естетика;der Determinismus|—|детермінізм;die Kausalität|—|каузальність;die Subjektivität|—|суб'єктивність;die Objektivität|—|об'єктивність;die Dialektik|—|діалектика;das Paradigma|Paradigmen|парадигма;die Kontingenz|—|випадковість буття;die Transzendenz|—|трансцендентність;die Immanenz|—|іманентність;die Legitimation|-en|легітимація;die Rechtfertigung|-en|виправдання;der Sinnzusammenhang|¨-e|смисловий зв'язок;begrifflich|—|понятійний;normativ|—|нормативний;deskriptiv|—|описовий;metaphysisch|—|метафізичний`,
"Дієслова високого стилю":`erörtern|—|розглядати докладно;bekunden|—|засвідчувати;anmuten|—|справляти враження;verweisen auf|—|відсилати до;obliegen|—|належати до обов'язків;bedürfen|—|потребувати (Gen.);gebieten|—|веліти;entbehren|—|бути позбавленим;verharren|—|застигати;anhaften|—|бути притаманним;innewohnen|—|бути властивим;widerfahren|—|спіткати;ereilen|—|настигнути;durchdringen|—|пронизувати;entfalten|—|розгортати;bewahren|—|зберігати;vermögen|—|бути спроможним;zeitigen|—|давати результат;hegen|—|плекати;walten|—|панувати`,
"Ділова риторика":`die Tagesordnung|-en|порядок денний;das Protokoll|-e|протокол;die Beschlussfassung|-en|ухвалення рішення;die Zielsetzung|-en|постановка цілей;die Priorisierung|-en|розставлення пріоритетів;der Handlungsbedarf|—|потреба діяти;die Rahmenbedingungen|—|рамкові умови;der Sachzwang|¨-e|об'єктивний примус;die Federführung|—|провідна роль;die Abstimmungsrunde|-n|раунд узгодження;der Meilenstein|-e|віха;das Zwischenergebnis|-se|проміжний результат;die Eskalation|-en|ескалація;die Deeskalation|-en|деескалація;der Kompromissvorschlag|¨-e|компромісна пропозиція;unterbreiten|—|подавати пропозицію;erwirken|—|домогтися;durchsetzen|—|впроваджувати;abwickeln|—|проводити, згортати;beschließen|—|ухвалювати`,
"Сполучники C1":`insoweit|—|остільки;wenngleich|—|хоча й;obgleich|—|хоча;wobei|—|причому;wodurch|—|завдяки чому;wonach|—|згідно з чим;woraufhin|—|після чого;sodann|—|потім;dahingehend|—|у тому сенсі;insofern als|—|остільки, оскільки;umso mehr als|—|тим паче що;geschweige denn|—|не кажучи вже про;ungeachtet|—|незважаючи на;kraft|—|силою чого;zwecks|—|з метою;mangels|—|через відсутність;anhand|—|на основі;mittels|—|за допомогою;seitens|—|з боку;binnen|—|протягом`,
"Емоційні відтінки":`die Bestürzung|—|приголомшення;die Empörung|—|обурення;die Entrüstung|—|моральне обурення;die Zerknirschung|—|розкаяння;die Beklommenheit|—|тривожна скутість;die Euphorie|—|ейфорія;die Melancholie|—|меланхолія;die Verbitterung|—|озлобленість;die Ergriffenheit|—|зворушення;die Fassungslosigkeit|—|розгубленість;die Erleichterung|-en|полегшення;die Genugtuung|—|задоволення від справедливості;die Wehrlosigkeit|—|беззахисність;die Zärtlichkeit|-en|ніжність;die Verwunderung|—|подив;überwältigt|—|приголомшений;fassungslos|—|ошелешений;zerknirscht|—|сповнений каяття;ergriffen|—|зворушений;beschwingt|—|піднесений`,
"Стійкі порівняння":`wie aus dem Ei gepellt|—|з голочки;wie ein Buch reden|—|говорити без упину;wie die Faust aufs Auge|—|як п'яте колесо;wie am Schnürchen|—|як по маслу;wie ein Fisch im Wasser|—|як риба у воді;wie auf Nadeln sitzen|—|сидіти як на голках;wie vom Erdboden verschluckt|—|як крізь землю провалився;wie ein Elefant im Porzellanladen|—|як слон у посудній крамниці;wie Pech und Schwefel|—|нерозлийвода;wie ein rotes Tuch|—|як червона ганчірка;ein Dorn im Auge sein|—|бути більмом на оці;auf die lange Bank schieben|—|відкладати в довгий ящик;das Kind mit dem Bade ausschütten|—|перегнути палицю;Perlen vor die Säue werfen|—|метати бісер;reinen Wein einschenken|—|сказати правду;die Kirche im Dorf lassen|—|не перебільшувати;alle Hebel in Bewegung setzen|—|задіяти всі важелі;auf Nummer sicher gehen|—|діяти напевно;den Bock zum Gärtner machen|—|пустити цапа в город;ins Blaue hinein|—|навмання`,
"Наукова мова":`die Fragestellung|-en|постановка питання;der Untersuchungsgegenstand|¨-e|об'єкт дослідження;die Stichprobe|-n|вибірка;die Signifikanz|—|статистична значущість;die Validität|—|валідність;die Reliabilität|—|надійність;die Kausalannahme|-n|припущення про причинність;der Befund|-e|результат обстеження;die Datenerhebung|-en|збір даних;die Auswertung|-en|опрацювання даних;die Replikation|-en|відтворення дослідження;der Forschungsstand|—|стан дослідження;die Operationalisierung|-en|операціоналізація;die Verzerrung|-en|викривлення;methodisch|—|методичний;quantitativ|—|кількісний;qualitativ|—|якісний;evident|—|очевидний;hypothetisch|—|гіпотетичний;fundiert|—|обґрунтований`,
"Іронія й критика":`die Anspielung|-en|натяк;der Seitenhieb|-e|шпилька;der Zynismus|—|цинізм;die Ironie|-n|іронія;der Sarkasmus|—|сарказм;die Polemik|-en|полеміка;die Schmähung|-en|паплюження;die Herabsetzung|-en|приниження;die Blamage|-n|ганьба;der Vorwurf|¨-e|докір;die Rüge|-n|догана;beschönigen|—|прикрашати;bloßstellen|—|виставляти на посміх;anprangern|—|таврувати;geißeln|—|бичувати;spotten|—|глузувати;sticheln|—|шпигати словами;süffisant|—|самовдоволено-іронічний;abschätzig|—|зневажливий;hämisch|—|зловтішний`,
"Історія й пам'ять":`die Zäsur|-en|злам, цезура;der Umbruch|¨-e|перелом;die Wende|-n|поворот;der Aufstand|¨-e|повстання;die Besatzung|-en|окупація;der Widerstand|¨-e|опір;die Befreiung|-en|визволення;die Vertreibung|-en|вигнання;die Aufarbeitung|-en|переосмислення минулого;die Erinnerungskultur|-en|культура пам'яті;das Vermächtnis|-se|спадок;die Kontinuität|-en|тяглість;der Bruch|¨-e|розрив;die Verfolgung|-en|переслідування;der Völkermord|-e|геноцид;die Wiedergutmachung|-en|відшкодування;das Zeitzeugnis|-se|свідчення очевидця;kollektiv|—|колективний;historisch|—|історичний;geprägt von|—|позначений чимось`,
"Розмовні звороти ч.2":`das ist mir schnuppe|—|мені байдуже;jetzt geht's los|—|ну почалося;da ist der Wurm drin|—|тут щось не так;das kannst du knicken|—|можеш забути;mir platzt der Kragen|—|у мене урвався терпець;ich bin platt|—|я в шоці;das ist ja der Hammer|—|оце так;na und?|—|і що з того?;von wegen!|—|та де там!;das war's|—|на цьому все;ich halt's nicht aus|—|я цього не витримую;lass gut sein|—|та годі вже;mach mal halblang|—|не перебільшуй;das hat gesessen|—|це влучило;Butter bei die Fische|—|переходь до суті;das kommt nicht in die Tüte|—|про це й мови нема;der Groschen ist gefallen|—|нарешті дійшло;auf gut Glück|—|навмання;klipp und klar|—|чітко і ясно;in null Komma nichts|—|миттю`});

