/* ================= ВІДЕО ДНЯ ================= */
/* формат: назва каналу | пошуковий запит на YouTube
   Посилання ведуть у пошук YouTube за запитом — так вони не «протухають»,
   коли автор перезаливає відео. Канали справжні й перевірені. */
const VID={};
VID.A1=`DW Deutsch lernen|Nicos Weg A1 Folge 1 Hallo;Learn German with Anja|Zahlen und Uhrzeit auf Deutsch lernen;DW Deutsch lernen|Nicos Weg A1 Wohnung Zimmer Möbel;Easy German|Essen und Trinken Wortschatz A1;DW Deutsch lernen|Nicos Weg A1 Wegbeschreibung Stadt;Deutsch mit Marija|Kleidung einkaufen Dialog A1;Learn German with Anja|Körper und Krankheiten Wortschatz;24h Deutsch|Die wichtigsten deutschen Verben A1;Deutsch mit Marija|Adjektive Gegenteile A1;Learn German with Anja|Artikel der die das Grundlagen;Easy German|Farben und Formen auf Deutsch;DW Deutsch lernen|Nicos Weg A1 Schule und Lernen;Deutsch mit Marija|Tiere auf Deutsch A1;Easy German|In der Küche Wortschatz Deutsch;DW Deutsch lernen|Nicos Weg A1 Freizeit und Hobbys;Easy German|Feste und Feiertage in Deutschland;24h Deutsch|Verkehrsmittel und Bewegung Deutsch A1;Deutsch mit Marija|Hausarbeit Wortschatz Deutsch;Learn German with Anja|W-Fragen Fragewörter Deutsch;Easy German|Höfliche Ausdrücke Deutsch Alltag`;
VID.A2=`DW Deutsch lernen|Nicos Weg A2 Beruf und Arbeit;Easy German|Geld und Bezahlen in Deutschland;DW Deutsch lernen|Nicos Weg A2 Reisen und Urlaub;Deutsch mit Marija|Wetter und Jahreszeiten Deutsch A2;DW Deutsch lernen|Nicos Weg A2 Behörden Formulare;Easy German|Gefühle auf Deutsch ausdrücken;24h Deutsch|Perfekt bilden A2 Deutsch;Deutsch mit Marija|Adjektivdeklination A2 einfach erklärt;Learn German with Anja|Wechselpräpositionen Akkusativ Dativ;24h Deutsch|Temporale Konnektoren als wenn wann;Easy German|Beim Arzt Dialog Deutsch A2;DW Deutsch lernen|Wohnungssuche Mietvertrag Deutsch;Easy German|Im Restaurant bestellen Deutsch;Deutsch mit Marija|Sport Wortschatz Deutsch A2;DW Deutsch lernen|Anmeldung Bürgeramt Deutschland erklärt;Easy German|Menschen beschreiben Aussehen Charakter;Deutsch mit Marija|Handy Internet Wortschatz Deutsch;DW Deutsch lernen|Am Bahnhof und am Flughafen Deutsch;24h Deutsch|Trennbare Verben Deutsch erklärt;Learn German with Anja|Häufigkeitsadverbien Deutsch A2`;
VID.B1=`DW Deutsch lernen|Nicos Weg B1 Ausbildung Studium;Easy German|Bewerbung und Vorstellungsgespräch Deutsch;DW Deutsch lernen|Nicos Weg B1 Wohnen in Deutschland;Easy German|Gesundheitssystem Deutschland erklärt;Easy German|Gesellschaft und Zusammenleben Deutschland;Deutsch mit Rieke|Technik Wortschatz Deutsch B1;24h Deutsch|Nomen-Verb-Verbindungen B1;Learn German with Anja|Verben mit Präpositionen B1 Liste;Deutsch mit Marija|Charaktereigenschaften Deutsch B1;24h Deutsch|Konnektoren obwohl trotzdem deshalb;Easy German|Arbeitsalltag im Büro Deutsch;Slow German mit Annik Rubens|Medien in Deutschland;Easy German|Mülltrennung und Recycling in Deutschland;Easy German|Leben als Ausländer in Deutschland;Slow German mit Annik Rubens|Geld und Sparen in Deutschland;Slow German mit Annik Rubens|Kultur und Museen in Deutschland;Easy German|Öffentliche Verkehrsmittel Deutschland;24h Deutsch|Konjunktiv II höfliche Bitten B1;Learn German with Anja|Reflexive Verben Deutsch B1;24h Deutsch|Argumentieren auf Deutsch B1`;
VID.B2=`Deutsch mit Benjamin|Politik Wortschatz Deutsch B2;Slow German mit Annik Rubens|Deutsche Wirtschaft erklärt;Easy German|Medien und Nachrichten Deutschland;Deutsch mit Rieke|Umwelt und Klima Wortschatz B2;Slow German mit Annik Rubens|Wissenschaft in Deutschland;Deutsch mit Benjamin|Rechtssprache Deutsch B2;Deutsch mit Benjamin|Abstrakte Verben B2 Wortschatz;24h Deutsch|Komparativ Superlativ Steigerung B2;Deutsch mit Benjamin|Formelle Briefe schreiben B2;Deutsch mit Benjamin|Konnektoren B2 Übersicht;Easy German|Arbeitsmarkt in Deutschland;Easy German|Das deutsche Schulsystem erklärt;Slow German mit Annik Rubens|Krankenversicherung Deutschland;Deutsch mit Rieke|Digitalisierung Wortschatz Deutsch;Easy German|Wohnungsmarkt in deutschen Städten;Deutsch mit Benjamin|Grafik beschreiben Statistik B2;Deutsch mit Benjamin|Diskussion und Verhandlung Deutsch B2;Deutsch mit Benjamin|Kausale Zusammenhänge ausdrücken B2;Deutsch mit Benjamin|Nominalisierung Deutsch B2;Deutsch mit Benjamin|Funktionsverbgefüge B2 C1`;
VID.C1=`Deutsch mit Benjamin|Akademischer Wortschatz C1;Deutsch mit Benjamin|Feste Wendungen C1 Deutsch;Easy German|Modalpartikeln doch mal eben erklärt;Easy German|Deutsche Redewendungen erklärt;Deutsch mit Benjamin|Gehobene Sprache Deutsch C1;Deutsch mit Benjamin|Synonyme unterscheiden C1;Slow German mit Annik Rubens|Psychologie und Philosophie Deutsch;Deutsch mit Benjamin|Amtssprache Behördendeutsch verstehen;Easy German|Umgangssprache auf der Straße;Deutsch mit Benjamin|Literarische Texte lesen C1;Deutsch mit Benjamin|Wissenschaftlich argumentieren C1;Deutsch mit Benjamin|Vertragssprache Deutsch verstehen;Easy German|Wie deutsche Medien argumentieren;Deutsch mit Benjamin|Gefühle differenziert ausdrücken C1;Slow German mit Annik Rubens|Deutsche Geschichte Erinnerungskultur;Slow German mit Annik Rubens|Ethik Debatten in Deutschland;Deutsch mit Benjamin|Metaphern im Deutschen C1;Easy German|Slang und Jugendsprache Deutsch;Deutsch mit Benjamin|Wortbildung Präfixe Suffixe Deutsch;Deutsch mit Benjamin|Diskursmarker C1 Textkohärenz`;
