/* ---- B1 · додаткові 200 ---- */
VN.B1 = {
"Робочі процеси":`die Besprechung|-en|нарада;der Auftrag|¨-e|замовлення;die Zusammenarbeit|—|співпраця;das Protokoll|-e|протокол;die Zuständigkeit|-en|компетенція;der Ablauf|¨-e|перебіг;die Abteilung|-en|відділ;der Vorgesetzte|-n|керівник;der Kollege|-n|колега;die Schicht|-en|зміна;die Überstunde|-n|понаднормова;der Vertrag|¨-e|договір;kündigen|—|звільняти(ся);sich bewerben|—|подавати заяву на роботу;der Lebenslauf|¨-e|резюме;das Vorstellungsgespräch|-e|співбесіда;die Probezeit|-en|випробний термін;das Gehalt|¨-er|зарплата;befördern|—|підвищувати;die Weiterbildung|-en|підвищення кваліфікації`,
"Медіа й новини":`die Sendung|-en|передача;der Bericht|-e|репортаж;die Schlagzeile|-n|заголовок;die Quelle|-n|джерело;der Journalist|-en|журналіст;das Interview|-s|інтерв'ю;die Zeitschrift|-en|журнал;der Beitrag|¨-e|допис, внесок;die Werbung|-en|реклама;der Zuschauer|-|глядач;der Leser|-|читач;veröffentlichen|—|публікувати;berichten|—|повідомляти;recherchieren|—|досліджувати;die Meinung|-en|думка;der Kommentar|-e|коментар;glaubwürdig|—|достовірний;objektiv|—|об'єктивний;die Öffentlichkeit|—|громадськість;die Reichweite|-n|охоплення`,
"Довкілля й переробка":`der Umweltschutz|—|охорона довкілля;die Mülltrennung|—|сортування сміття;das Recycling|—|переробка;die Verpackung|-en|упаковка;der Kunststoff|-e|пластик;die Energie|-n|енергія;erneuerbar|—|відновлюваний;der Klimawandel|—|зміна клімату;die Verschmutzung|-en|забруднення;die Emission|-en|викид;sparen|—|заощаджувати;vermeiden|—|уникати;verbrauchen|—|споживати;nachhaltig|—|сталий;die Ressource|-n|ресурс;der Verbrauch|—|споживання;die Anlage|-n|установка;schädlich|—|шкідливий;umweltfreundlich|—|екологічний;der Abfalleimer|-|смітник`,
"Міграція й інтеграція":`die Aufenthaltserlaubnis|-se|дозвіл на проживання;die Staatsbürgerschaft|-en|громадянство;der Flüchtling|-e|біженець;die Herkunft|¨-e|походження;die Integration|-en|інтеграція;der Sprachkurs|-e|мовний курс;die Anerkennung|-en|визнання;der Abschluss|¨-e|диплом;die Heimat|-en|батьківщина;die Zuwanderung|-en|імміграція;auswandern|—|емігрувати;einwandern|—|імігрувати;sich anpassen|—|пристосовуватися;die Erfahrung|-en|досвід;die Chance|-n|шанс;die Schwierigkeit|-en|труднощі;die Unterstützung|-en|підтримка;der Antragsteller|-|заявник;die Genehmigung|-en|дозвіл;die Voraussetzung|-en|передумова`,
"Гроші й фінанси":`das Konto|Konten|рахунок;die Überweisung|-en|переказ;der Kredit|-e|кредит;die Rate|-n|платіж частинами;die Zinsen|—|відсотки;die Schulden|—|борги;das Einkommen|-|дохід;die Ausgabe|-n|витрата;die Steuer|-n|податок;die Rente|-n|пенсія;die Rechnung|-en|рахунок до сплати;sparen|—|заощаджувати;investieren|—|інвестувати;sich leisten|—|дозволити собі;die Versicherung|-en|страховка;der Betrag|¨-e|сума;das Budget|-s|бюджет;überweisen|—|переказувати;abheben|—|знімати гроші;die Gebühr|-en|комісія`,
"Мистецтво й культура":`das Gemälde|-|картина;die Ausstellung|-en|виставка;der Künstler|-|митець;die Bühne|-n|сцена;die Aufführung|-en|вистава;der Roman|-e|роман;die Dichtung|-en|поезія;der Schriftsteller|-|письменник;das Publikum|—|публіка;die Kritik|-en|критика;der Eindruck|¨-e|враження;das Werk|-e|твір;darstellen|—|зображати;aufführen|—|показувати виставу;die Kultur|-en|культура;die Tradition|-en|традиція;das Erbe|—|спадщина;beeindruckend|—|вражаючий;künstlerisch|—|мистецький;die Vorstellung|-en|вистава, уявлення`,
"Транспорт і місто":`der Verkehr|—|дорожній рух;der Stau|-s|затор;die Fußgängerzone|-n|пішохідна зона;der Radweg|-e|велодоріжка;die Umleitung|-en|об'їзд;der Fahrplan|¨-e|розклад;die Verkehrsmittel|—|транспортні засоби;die Innenstadt|¨-e|центр міста;der Stadtrand|¨-er|околиця;die Baustelle|-n|будмайданчик;der Bewohner|-|мешканець;die Gemeinde|-n|громада;die Infrastruktur|-en|інфраструктура;der Lärm|—|шум;die Sicherheit|-en|безпека;überfüllt|—|переповнений;bequem|—|зручний;erreichbar|—|досяжний;die Entfernung|-en|відстань;die Verbindung|-en|сполучення`,
"Наміри й модальність":`beabsichtigen|—|мати намір;vorhaben|—|планувати;sich vornehmen|—|намірятися;versuchen|—|намагатися;schaffen|—|встигати, справлятися;gelingen|—|вдаватися;verzichten|—|відмовлятися;sich entscheiden|—|вирішувати;zögern|—|вагатися;überlegen|—|обмірковувати;bereuen|—|шкодувати;wagen|—|наважуватися;erlauben|—|дозволяти;verbieten|—|забороняти;zwingen|—|змушувати;vermeiden|—|уникати;bevorzugen|—|надавати перевагу;ablehnen|—|відхиляти;zustimmen|—|погоджуватися;durchsetzen|—|домагатися`,
"Зворотні дієслова":`sich freuen|—|радіти;sich ärgern|—|злитися;sich erinnern|—|згадувати;sich interessieren|—|цікавитися;sich kümmern|—|піклуватися;sich beschweren|—|скаржитися;sich bedanken|—|дякувати;sich verabreden|—|домовлятися про зустріч;sich beeilen|—|поспішати;sich erholen|—|відпочивати;sich gewöhnen|—|звикати;sich verlieben|—|закохуватися;sich streiten|—|сваритися;sich entschuldigen|—|вибачатися;sich vorstellen|—|уявляти;sich unterhalten|—|розмовляти;sich konzentrieren|—|зосереджуватися;sich verlassen|—|покладатися;sich weigern|—|відмовлятися;sich lohnen|—|бути вартим`,
"Оцінка й аргументація":`einerseits|—|з одного боку;andererseits|—|з іншого боку;der Vorteil|-e|перевага;der Nachteil|-e|недолік;das Argument|-e|аргумент;der Grund|¨-e|причина;die Folge|-n|наслідок;behaupten|—|стверджувати;bezweifeln|—|сумніватися;betonen|—|наголошувати;vergleichen|—|порівнювати;begründen|—|обґрунтовувати;widersprechen|—|заперечувати;überzeugen|—|переконувати;zugeben|—|визнавати;einschätzen|—|оцінювати;der Standpunkt|-e|точка зору;umstritten|—|спірний;überzeugend|—|переконливий;der Kompromiss|-e|компроміс`
};
