/* ---- A2 · додаткові 200 ---- */
VN.A2 = {
"Лікар і аптека":`die Praxis|Praxen|практика лікаря;der Termin|-e|запис, візит;die Versicherung|-en|страхування;das Rezept|-e|рецепт;die Tablette|-n|таблетка;die Salbe|-n|мазь;die Spritze|-n|укол;die Untersuchung|-en|обстеження;die Behandlung|-en|лікування;der Husten|—|кашель;der Schnupfen|-|нежить;die Grippe|-n|грип;die Wunde|-n|рана;die Allergie|-n|алергія;sich fühlen|—|почуватися;weh tun|—|боліти;heilen|—|зцілювати;der Notfall|¨-e|невідкладний випадок;der Krankenschein|-e|лікарняний;die Gesundheit|—|здоров'я`,
"Оренда й квартира":`der Vermieter|-|орендодавець;der Mieter|-|орендар;der Mietvertrag|¨-e|договір оренди;die Kaution|-en|застава;die Nebenkosten|—|комунальні витрати;der Quadratmeter|-|квадратний метр;der Balkon|-e|балкон;der Keller|-|підвал;der Aufzug|¨-e|ліфт;die Heizung|-en|опалення;der Strom|—|електрика;das Erdgeschoss|-e|перший поверх;der Stock|Stockwerke|поверх;die Besichtigung|-en|огляд;einziehen|—|заселятися;ausziehen|—|виселятися;umziehen|—|переїжджати;möbliert|—|мебльований;die Hausordnung|-en|правила будинку;die Nachbarschaft|-en|сусідство`,
"Кафе й ресторан":`die Speisekarte|-n|меню;die Vorspeise|-n|закуска;das Hauptgericht|-e|основна страва;die Nachspeise|-n|десерт;die Rechnung|-en|рахунок;das Trinkgeld|-er|чайові;der Kellner|-|офіціант;die Bedienung|-en|обслуговування;bestellen|—|замовляти;empfehlen|—|рекомендувати;reservieren|—|бронювати;lecker|—|смачний;satt|—|ситий;der Durst|—|спрага;der Hunger|—|голод;die Portion|-en|порція;scharf|—|гострий;süß|—|солодкий;salzig|—|солоний;sauer|—|кислий`,
"Спорт":`das Training|-s|тренування;die Mannschaft|-en|команда;der Verein|-e|клуб;das Spielfeld|-er|поле;das Tor|-e|ворота, гол;der Sieg|-e|перемога;die Niederlage|-n|поразка;der Wettkampf|¨-e|змагання;der Schiedsrichter|-|суддя;die Meisterschaft|-en|чемпіонат;trainieren|—|тренуватися;gewinnen|—|вигравати;verlieren|—|програвати;werfen|—|кидати;springen|—|стрибати;der Ball|¨-e|м'яч;das Fitnessstudio|-s|спортзал;die Bewegung|-en|рух;müde|—|втомлений;fit|—|у формі`,
"Установи й документи":`das Amt|¨-er|відомство;der Antrag|¨-e|заява;das Formular|-e|бланк;die Unterschrift|-en|підпис;der Ausweis|-e|посвідчення;der Reisepass|¨-e|закордонний паспорт;die Anmeldung|-en|реєстрація;die Bescheinigung|-en|довідка;die Gebühr|-en|збір, мито;der Stempel|-|печатка;die Frist|-en|термін;beantragen|—|подавати заяву;ausfüllen|—|заповнювати;unterschreiben|—|підписувати;der Beamte|-n|чиновник;der Schalter|-|віконце;die Kopie|-n|копія;gültig|—|дійсний;nötig|—|потрібний;die Behörde|-n|орган влади`,
"Зовнішність і характер":`schlank|—|стрункий;dick|—|товстий;groß|—|високий;klein|—|низький;blond|—|білявий;hübsch|—|гарненький;attraktiv|—|привабливий;freundlich|—|привітний;höflich|—|ввічливий;ehrlich|—|чесний;faul|—|лінивий;fleißig|—|старанний;lustig|—|веселий;ernst|—|серйозний;ruhig|—|спокійний;nervös|—|знервований;geduldig|—|терплячий;neugierig|—|допитливий;mutig|—|сміливий;schüchtern|—|сором'язливий`,
"Телефон та інтернет":`das Handy|-s|мобільний;der Anruf|-e|дзвінок;die Nachricht|-en|повідомлення;die Nummer|-n|номер;der Akku|-s|акумулятор;das Ladegerät|-e|зарядка;die App|-s|застосунок;das Passwort|¨-er|пароль;das Konto|Konten|акаунт;die Webseite|-n|вебсайт;herunterladen|—|завантажувати;hochladen|—|вивантажувати;anrufen|—|дзвонити;auflegen|—|класти слухавку;speichern|—|зберігати;löschen|—|видаляти;der Bildschirm|-e|екран;das Netz|-e|мережа;der Empfang|—|прийом сигналу;online|—|онлайн`,
"Потяг і літак":`der Bahnsteig|-e|перон;das Gleis|-e|колія;der Waggon|-s|вагон;der Sitzplatz|¨-e|сидяче місце;die Verspätung|-en|запізнення;der Anschluss|¨-e|пересадка;umsteigen|—|пересідати;abfahren|—|відправлятися;ankommen|—|прибувати;der Koffer|-|валіза;das Gepäck|—|багаж;der Rucksack|¨-e|рюкзак;die Grenze|-n|кордон;der Zoll|¨-e|митниця;das Ticket|-s|квиток;der Flug|¨-e|рейс;landen|—|приземлятися;starten|—|злітати;buchen|—|бронювати;die Ankunft|¨-e|прибуття`,
"Розділові дієслова":`aufstehen|—|вставати;anfangen|—|починати;aufhören|—|припиняти;mitkommen|—|іти разом;mitbringen|—|приносити з собою;zumachen|—|закривати;aufmachen|—|відкривати;einkaufen|—|робити покупки;fernsehen|—|дивитися телевізор;abholen|—|забирати;vorbereiten|—|готувати;teilnehmen|—|брати участь;zurückkommen|—|повертатися;weitermachen|—|продовжувати;ausgehen|—|виходити гуляти;anziehen|—|одягати;ausziehen|—|знімати одяг;vorstellen|—|представляти;nachdenken|—|роздумувати;zuhören|—|слухати`,
"Прислівники частоти й місця":`immer|—|завжди;oft|—|часто;manchmal|—|іноді;selten|—|рідко;nie|—|ніколи;meistens|—|переважно;täglich|—|щодня;wöchentlich|—|щотижня;bald|—|скоро;sofort|—|негайно;oben|—|вгорі;unten|—|внизу;vorne|—|спереду;hinten|—|позаду;draußen|—|надворі;drinnen|—|усередині;überall|—|скрізь;nirgends|—|ніде;irgendwo|—|десь;dazwischen|—|поміж`
};
