/* ---- A1 · третя й четверта сотні (20 нових тем) ----
   Пишемо з запасом (по 24 слова): збірник візьме перші 20 унікальних,
   решта піде в резерв, якщо слово вже трапилося в іншій темі.        */
VX.A1 = {
"Погода щодня":`der Regen|—|дощ;der Schnee|—|сніг;der Wind|-e|вітер;die Wolke|-n|хмара;der Nebel|-|туман;das Gewitter|-|гроза;der Blitz|-e|блискавка;der Donner|-|грім;der Frost|¨-e|мороз;das Eis|—|лід;der Grad|-e|градус;die Temperatur|-en|температура;sonnig|—|сонячно;wolkig|—|хмарно;windig|—|вітряно;neblig|—|туманно;regnerisch|—|дощовий;heiß|—|спекотний;kühl|—|прохолодний;mild|—|м'який;frieren|—|мерзнути;schneien|—|сніжити;regnen|—|дощити;die Hitze|—|спека`,
"Меблі й освітлення":`das Regal|-e|полиця;die Kommode|-n|комод;der Sessel|-|крісло;der Teppich|-e|килим;der Vorhang|¨-e|штора;das Kissen|-|подушка;die Matratze|-n|матрац;der Hocker|-|табурет;die Steckdose|-n|розетка;der Rahmen|-|рама;das Bild|-er|картина;der Papierkorb|¨-e|кошик для сміття;die Schublade|-n|шухляда;der Nachttisch|-e|тумбочка;die Stehlampe|-n|торшер;der Wecker|-|будильник;das Bettlaken|-|простирадло;die Gardine|-n|гардина;die Kerze anzünden|—|запалити свічку;das Licht|-er|світло;der Sicherungskasten|¨|щиток;die Klimaanlage|-n|кондиціонер;der Ventilator|-en|вентилятор;das Möbelstück|-e|предмет меблів`,
"Фрукти":`die Birne|-n|груша;die Banane|-n|банан;die Orange|-n|апельсин;die Zitrone|-n|лимон;die Traube|-n|виноград;die Erdbeere|-n|полуниця;die Kirsche|-n|вишня;der Pfirsich|-e|персик;die Pflaume|-n|слива;die Melone|-n|диня;die Ananas|-|ананас;die Himbeere|-n|малина;die Blaubeere|-n|чорниця;die Aprikose|-n|абрикос;die Feige|-n|інжир;die Nuss|¨-e|горіх;die Mandel|-n|мигдаль;die Beere|-n|ягода;reif|—|стиглий;saftig|—|соковитий;schälen|—|чистити від шкірки;der Kern|-e|кісточка;die Schale|-n|шкірка;der Fruchtsaft|¨-e|фруктовий сік`,
"Овочі та зелень":`die Tomate|-n|помідор;die Gurke|-n|огірок;die Zwiebel|-n|цибуля;der Knoblauch|—|часник;die Möhre|-n|морква;der Kohl|-e|капуста;der Salat|-e|салат;der Pilz|-e|гриб;die Bohne|-n|квасоля;die Erbse|-n|горох;der Paprika|-s|болгарський перець;die Aubergine|-n|баклажан;die Zucchini|-|кабачок;der Kürbis|-se|гарбуз;der Spinat|—|шпинат;die Petersilie|—|петрушка;der Dill|—|кріп;die Rote Bete|—|буряк;der Sellerie|—|селера;der Lauch|-e|цибуля-порей;roh|—|сирий;gekocht|—|варений;frisch|—|свіжий;das Kraut|¨-er|зілля`,
"Солодощі й випічка":`die Schokolade|-n|шоколад;das Bonbon|-s|цукерка;das Eis essen|—|їсти морозиво;die Torte|-n|торт;das Gebäck|-e|випічка;der Keks|-e|печиво;die Brezel|-n|крендель;das Brötchen|-|булочка;der Honig|-e|мед;die Marmelade|-n|варення;die Sahne|—|вершки;der Pudding|-s|пудинг;der Krapfen|-|пампушка;der Lebkuchen|-|пряник;die Waffel|-n|вафля;das Croissant|-s|круасан;der Teig|-e|тісто;das Mehl|-e|борошно;die Hefe|—|дріжджі;das Rezept nachbacken|—|пекти за рецептом;süßen|—|підсолоджувати;lecker riechen|—|смачно пахнути;knusprig|—|хрусткий;zart|—|ніжний`,
"Прості професії":`der Bäcker|-|пекар;der Koch|¨-e|кухар;der Fahrer|-|водій;der Verkäufer|-|продавець;die Krankenschwester|-n|медсестра;der Polizist|-en|поліцейський;der Feuerwehrmann|¨-er|пожежник;der Friseur|-e|перукар;der Kellner|-|офіціант;der Gärtner|-|садівник;der Maler|-|маляр;der Tischler|-|столяр;der Elektriker|-|електрик;der Mechaniker|-|механік;der Landwirt|-e|фермер;der Briefträger|-|листоноша;der Pilot|-en|пілот;der Musiker|-|музикант;der Sänger|-|співак;der Maurer|-|муляр;der Schneider|-|кравець;der Fleischer|-|м'ясник;der Bibliothekar|-e|бібліотекар;der Zahnarzthelfer|-|асистент стоматолога`,
"У супермаркеті":`der Einkaufswagen|-|візок;der Korb|¨-e|кошик;das Regal durchsuchen|—|шукати на полиці;die Tüte|-n|пакет;die Dose|-n|бляшанка;die Packung|-en|упаковка;das Pfund|-e|фунт;das Kilo|-s|кілограм;das Gramm|-e|грам;der Liter|-|літр;das Angebot|-e|акційна пропозиція;der Rabatt|-e|знижка;das Haltbarkeitsdatum|-daten|термін придатності;die Tiefkühlware|-n|заморожені продукти;die Kasse bezahlen|—|платити на касі;das Kleingeld|—|дрібні гроші;der Schein|-e|купюра;die Münze|-n|монета;wiegen|—|важити;einpacken lassen|—|попросити запакувати;die Abteilung suchen|—|шукати відділ;der Vorrat|¨-e|запас;abgelaufen|—|прострочений;günstig|—|вигідний`,
"Числа та лічба":`null|—|нуль;elf|—|одинадцять;zwölf|—|дванадцять;zwanzig|—|двадцять;dreißig|—|тридцять;vierzig|—|сорок;fünfzig|—|п'ятдесят;hundert|—|сто;tausend|—|тисяча;die Million|-en|мільйон;erste|—|перший;zweite|—|другий;dritte|—|третій;letzte|—|останній;die Hälfte|-n|половина;das Viertel|-|чверть;das Drittel|-|третина;das Paar|-e|пара;das Dutzend|-e|дюжина;doppelt|—|подвійний;einzeln|—|окремо;zählen|—|рахувати;rechnen|—|обчислювати;die Summe|-n|сума`,
"Прийменники місця":`auf|—|на;unter|—|під;über|—|над;neben|—|поряд;zwischen|—|між;hinter|—|за;vor dem Haus|—|перед будинком;an der Wand|—|на стіні;in der Ecke|—|у кутку;gegenüber vom Park|—|навпроти парку;entlang|—|уздовж;um … herum|—|навколо;innerhalb|—|усередині;außerhalb|—|поза межами;oberhalb|—|вище;unterhalb|—|нижче;inmitten|—|посеред;seitlich|—|збоку;rechts von|—|праворуч від;links von|—|ліворуч від;am Rand|—|скраю;in der Mitte|—|посередині;quer|—|навскіс;dahinter|—|позаду того`,
"Дієслова руху":`rennen|—|мчати;klettern|—|дертися;kriechen|—|повзти;rutschen|—|ковзати;hüpfen|—|підстрибувати;schieben|—|штовхати;ziehen|—|тягнути;heben|—|піднімати;drehen|—|обертати;rollen|—|котити;fallen|—|падати;stehen bleiben|—|зупинятися;sich bücken|—|нахилятися;sich strecken|—|потягуватися;eilen|—|поспішати;wandern gehen|—|іти в похід;schreiten|—|крокувати;stolpern|—|спотикатися;landen|—|приземлятися;abbiegen|—|повертати;überqueren|—|переходити;folgen|—|слідувати;begleiten|—|супроводжувати;sich nähern|—|наближатися`,
"Прості почуття":`froh|—|радісний;traurig|—|сумний;böse|—|сердитий;stolz|—|гордий;überrascht|—|здивований;enttäuscht|—|розчарований;aufgeregt|—|схвильований;erleichtert|—|заспокоєний;einsam|—|самотній;zufrieden|—|задоволений;ängstlich|—|боязкий;verwirrt|—|розгублений;dankbar|—|вдячний;eifersüchtig|—|ревнивий;gelangweilt|—|знуджений;begeistert|—|захоплений;lachen|—|сміятися;weinen|—|плакати;lächeln|—|усміхатися;seufzen|—|зітхати;sich schämen für|—|соромитися за;Angst haben|—|боятися;Spaß machen|—|тішити;das Gefühl|-e|почуття`,
"Ширша родина":`der Onkel|-|дядько;die Tante|-n|тітка;der Cousin|-s|двоюрідний брат;die Cousine|-n|двоюрідна сестра;der Neffe|-n|племінник;die Nichte|-n|племінниця;der Enkel|-|онук;die Enkelin|-nen|онучка;der Schwager|¨|шурин;die Schwägerin|-nen|своячка;die Schwiegermutter|¨|свекруха;der Schwiegervater|¨|свекор;der Ehemann|¨-er|чоловік у шлюбі;die Ehefrau|-en|дружина;das Paar sein|—|бути парою;die Hochzeit|-en|весілля;die Verwandtschaft|-en|родичі;der Vorfahre|-n|предок;die Generation|-en|покоління;der Zwilling|-e|близнюк;das Patenkind|-er|хрещеник;die Familie gründen|—|створити сім'ю;heiraten|—|одружуватися;verwandt|—|споріднений`,
"Взуття й аксесуари":`der Stiefel|-|чобіт;der Sandale|-n|сандаля;der Turnschuh|-e|кросівок;der Pantoffel|-n|капець;die Socke|-n|шкарпетка;die Strumpfhose|-n|колготи;der Gürtel|-|пасок;der Schal|-s|шарф;der Handschuh|-e|рукавичка;der Hut|¨-e|капелюх;die Kappe|-n|кепка;der Schmuck|—|прикраси;der Ring|-e|каблучка;die Kette|-n|ланцюжок;der Ohrring|-e|сережка;das Armband|¨-er|браслет;der Rucksack tragen|—|носити рюкзак;die Geldbörse|-n|гаманець;der Schirm|-e|парасоля;die Uhr tragen|—|носити годинник;der Knopf|¨-e|ґудзик;der Reißverschluss|¨-e|блискавка;die Tasche packen|—|пакувати сумку;anprobieren|—|міряти`,
"Будівлі та заклади":`das Rathaus|¨-er|ратуша;das Museum besuchen|—|відвідати музей;die Bäckerei|-en|пекарня;die Metzgerei|-en|м'ясна крамниця;das Café|-s|кафе;das Restaurant|-s|ресторан;das Hotel|-s|готель;das Stadion|Stadien|стадіон;die Bibliothek besuchen|—|ходити в бібліотеку;das Kino|-s|кінотеатр;die Tankstelle|-n|заправка;die Werkstatt|¨-en|майстерня;der Friseursalon|-s|перукарня;das Schwimmbad|¨-er|басейн;der Spielplatz|¨-e|дитячий майданчик;der Zoo|-s|зоопарк;der Turm|¨-e|вежа;die Burg|-en|фортеця;das Schloss|¨-er|замок;die Brauerei|-en|броварня;das Gebäude|-|будівля;der Eingang|¨-e|вхід;die Fassade|-n|фасад;das Dach|¨-er|дах`,
"Природа навколо":`der Baum|¨-e|дерево;der Wald|¨-er|ліс;die Wiese|-n|лука;das Feld|-er|поле;der Berg|-e|гора;das Tal|¨-er|долина;der Fluss|¨-e|річка;der See|-n|озеро;das Meer|-e|море;der Strand|¨-e|пляж;der Stein|-e|камінь;der Sand|-e|пісок;das Gras|¨-er|трава;das Blatt|¨-er|листок;der Ast|¨-e|гілка;die Wurzel|-n|корінь;der Busch|¨-e|кущ;die Insel|-n|острів;die Höhle|-n|печера;der Hügel|-|пагорб;der Bach|¨-e|струмок;der Wasserfall|¨-e|водоспад;die Landschaft|-en|краєвид;die Luft|¨-e|повітря`,
"Обличчя зблизька":`die Stirn|-en|чоло;die Wange|-n|щока;das Kinn|-e|підборіддя;die Lippe|-n|губа;die Zunge|-n|язик;die Augenbraue|-n|брова;die Wimper|-n|вія;der Bart|¨-e|борода;der Schnurrbart|¨-e|вуса;der Hals|¨-e|шия;die Schulter|-n|плече;der Ellbogen|-|лікоть;das Knie|-|коліно;der Finger|-|палець руки;der Zeh|-en|палець ноги;der Nagel|¨|ніготь;die Haut|¨-e|шкіра;der Knochen|-|кістка;das Gesicht|-er|обличчя;der Blick|-e|погляд;die Falte glätten|—|розгладити зморшку;blinzeln|—|кліпати;gähnen|—|позіхати;nicken|—|кивати`,
"Дитинство та іграшки":`der Ball spielen|—|грати м'ячем;die Puppe|-n|лялька;der Teddybär|-en|плюшевий ведмедик;der Bauklotz|¨-e|кубик;die Schaukel|-n|гойдалка;die Rutsche|-n|гірка;der Sandkasten|¨|пісочниця;das Dreirad|¨-er|триколісний велосипед;der Drachen|-|повітряний змій;die Murmel|-n|кулька;das Märchen|-|казка;das Lied singen|—|співати пісню;der Kinderwagen|-|дитячий візок;die Windel|-n|підгузок;der Schnuller|-|соска;das Spielzeug|-e|іграшка;die Kindheit|-en|дитинство;der Kindergeburtstag|-e|дитячий день народження;basteln|—|майструвати;schaukeln|—|гойдатися;verstecken|—|ховати;fangen|—|ловити;raten|—|вгадувати;zeichnen|—|малювати олівцем`,
"Матеріали й речовини":`das Holz|¨-er|деревина;das Metall|-e|метал;das Eisen|-|залізо;das Gold|-e|золото;das Silber|-|срібло;das Glas trinken|—|випити склянку;das Plastik|-|пластик;das Leder|-|шкіра як матеріал;die Wolle|-n|вовна;die Baumwolle|—|бавовна;die Seide|-n|шовк;der Stoff|-e|тканина;der Beton|-s|бетон;der Ziegel|-|цегла;der Ton|-e|глина;das Wachs|-e|віск;das Gummi|-s|гума;der Draht|¨-e|дріт;der Faden|¨|нитка;hart|—|твердий;weich|—|м'який;glatt|—|гладкий;rau|—|шорсткий;zerbrechlich|—|крихкий`,
"Прості сполучники":`und|—|і;oder|—|або;aber|—|але;denn|—|бо;sondern|—|а навпаки;weil|—|тому що;dass|—|що;wenn|—|якщо;als|—|коли одного разу;ob|—|чи;damit|—|щоб;obwohl|—|хоча;deshalb|—|тому;trotzdem|—|попри це;also|—|отже;zuerst|—|спершу;dann|—|потім;danach|—|після того;schließlich|—|нарешті;außerdem|—|крім того;zum Beispiel|—|наприклад;das heißt|—|тобто;einerseits …|—|з одного боку;sowohl … als auch|—|як … так і`,
"Ранок і вечір":`aufwachen|—|прокидатися;sich waschen|—|вмиватися;sich duschen|—|приймати душ;sich anziehen|—|одягатися;sich kämmen|—|розчісуватися;die Zähne putzen|—|чистити зуби;das Bett machen|—|застеляти ліжко;frühstücken|—|снідати;zur Arbeit gehen|—|іти на роботу;Mittag essen|—|обідати;sich ausruhen|—|відпочивати;spazieren gehen|—|гуляти;kochen lernen|—|учитися готувати;das Geschirr spülen|—|мити посуд;fernsehen schauen|—|дивитися телевізор;lesen vor dem Schlafen|—|читати перед сном;das Licht ausmachen|—|вимикати світло;einschlafen|—|засинати;träumen|—|снитися;schnarchen|—|хропіти;müde werden|—|втомлюватися;sich hinlegen|—|лягати;der Alltag|-e|повсякдення;die Gewohnheit|-en|звичка`
};
