/* ---- A1 · додаткові 200 ---- */
VN.A1 = {
"Кольори й форми":`rot|—|червоний;blau|—|синій;grün|—|зелений;gelb|—|жовтий;schwarz|—|чорний;weiß|—|білий;grau|—|сірий;braun|—|коричневий;rosa|—|рожевий;die Farbe|-n|колір;der Kreis|-e|коло;das Quadrat|-e|квадрат;die Linie|-n|лінія;der Punkt|-e|крапка;rund|—|круглий;eckig|—|кутастий;hell|—|світлий;dunkel|—|темний;bunt|—|барвистий;die Form|-en|форма`,
"Школа й навчання":`der Lehrer|-|учитель;die Lehrerin|-nen|учителька;der Schüler|-|учень;die Klasse|-n|клас;das Buch|¨-er|книга;das Heft|-e|зошит;der Bleistift|-e|олівець;das Papier|-e|папір;die Tafel|-n|дошка;die Aufgabe|-n|завдання;die Frage|-n|питання;die Antwort|-en|відповідь;das Wort|¨-er|слово;der Satz|¨-e|речення;die Sprache|-n|мова;die Note|-n|оцінка;der Unterricht|—|заняття;die Universität|-en|університет;der Kurs|-e|курс;die Prüfung|-en|іспит`,
"Тварини":`der Hund|-e|собака;die Katze|-n|кішка;das Pferd|-e|кінь;die Kuh|¨-e|корова;das Schwein|-e|свиня;das Schaf|-e|вівця;der Vogel|¨|птах;das Huhn|¨-er|курка;die Maus|¨-e|миша;der Bär|-en|ведмідь;der Wolf|¨-e|вовк;der Fuchs|¨-e|лис;das Tier|-e|тварина;die Biene|-n|бджола;die Fliege|-n|муха;der Hase|-n|заєць;die Ente|-n|качка;das Insekt|-en|комаха;der Löwe|-n|лев;der Elefant|-en|слон`,
"Кухня й посуд":`der Teller|-|тарілка;die Tasse|-n|чашка;das Glas|¨-er|склянка;die Gabel|-n|виделка;das Messer|-|ніж;der Löffel|-|ложка;der Topf|¨-e|каструля;die Pfanne|-n|сковорода;der Herd|-e|плита;der Kühlschrank|¨-e|холодильник;der Ofen|¨|духовка;die Flasche|-n|пляшка;die Serviette|-n|серветка;kochen|—|варити;braten|—|смажити;backen|—|пекти;schneiden|—|різати;die Mahlzeit|-en|прийом їжі;das Frühstück|-e|сніданок;das Abendessen|-|вечеря`,
"Хобі й вільний час":`das Hobby|-s|хобі;die Musik|—|музика;der Film|-e|фільм;das Spiel|-e|гра;der Sport|—|спорт;das Foto|-s|фото;die Reise|-n|подорож;das Lied|-er|пісня;singen|—|співати;tanzen|—|танцювати;malen|—|малювати;spielen|—|грати;schwimmen|—|плавати;laufen|—|бігати;wandern|—|ходити в походи;die Freizeit|—|вільний час;der Urlaub|-e|відпустка;das Konzert|-e|концерт;das Museum|Museen|музей;das Theater|-|театр`,
"Свята й дати":`der Geburtstag|-e|день народження;das Fest|-e|свято;Weihnachten|—|Різдво;Ostern|—|Великдень;das Geschenk|-e|подарунок;die Karte|-n|листівка;die Party|-s|вечірка;der Gast|¨-e|гість;die Einladung|-en|запрошення;feiern|—|святкувати;gratulieren|—|вітати;der Feiertag|-e|вихідний день;die Kerze|-n|свічка;der Kuchen|-|торт;die Blume|-n|квітка;das Glück|—|щастя;wünschen|—|бажати;einladen|—|запрошувати;der Januar|—|січень;der Dezember|—|грудень`,
"Транспорт і рух":`fahren|—|їхати;fliegen|—|летіти;gehen|—|йти;kommen|—|приходити;steigen|—|підійматися;die Fahrkarte|-n|квиток;der Fahrplan|¨-e|розклад;die Ampel|-n|світлофор;die Brücke|-n|міст;die Ecke|-n|ріг;die Kreuzung|-en|перехрестя;links|—|ліворуч;rechts|—|праворуч;geradeaus|—|прямо;der Weg|-e|шлях;die Richtung|-en|напрямок;schnell|—|швидкий;langsam|—|повільний;die Fahrt|-en|поїздка;das Taxi|-s|таксі`,
"Робота по дому":`putzen|—|прибирати;waschen|—|мити, прати;aufräumen|—|прибирати;wischen|—|витирати;die Wäsche|—|білизна;der Staubsauger|-|пилосос;die Seife|-n|мило;das Handtuch|¨-er|рушник;die Bürste|-n|щітка;der Eimer|-|відро;reparieren|—|ремонтувати;der Abfall|¨-e|відходи;die Ordnung|—|порядок;schmutzig|—|брудний;sauber|—|чистий;die Arbeit|-en|робота;helfen|—|допомагати;tragen|—|нести;räumen|—|звільняти;die Pflicht|-en|обов'язок`,
"Питальні слова":`wer|—|хто;was|—|що;wo|—|де;wann|—|коли;wie|—|як;warum|—|чому;woher|—|звідки;wohin|—|куди;welcher|—|який;wie viel|—|скільки;wie lange|—|як довго;wie oft|—|як часто;wozu|—|навіщо;womit|—|чим;wem|—|кому;wen|—|кого;wessen|—|чий;wieso|—|чого це;weshalb|—|з якої причини;was für ein|—|що за`,
"Ввічливість і вирази":`danke|—|дякую;bitte|—|будь ласка;entschuldigung|—|вибачте;tschüss|—|бувай;hallo|—|привіт;guten Tag|—|добрий день;auf Wiedersehen|—|до побачення;gern|—|охоче;natürlich|—|звісно;vielleicht|—|можливо;leider|—|на жаль;genau|—|саме так;klar|—|ясно;kein Problem|—|без проблем;alles Gute|—|усього доброго;viel Glück|—|щасти;wie geht's|—|як справи;mir geht es gut|—|у мене все добре;bis bald|—|до скорого;herzlich willkommen|—|ласкаво просимо`
};
