/* ---- C1 · додаткові 200 ---- */
VN.C1 = {
"Наукова аргументація":`die These|-n|теза;die Hypothese|-n|гіпотеза;die Prämisse|-n|засновок;die Schlussfolgerung|-en|висновок;die Evidenz|-en|доказовість;der Nachweis|-e|доказ;die Methodik|-en|методика;die Fragestellung|-en|постановка питання;der Befund|-e|результат дослідження;die Erkenntnis|-se|пізнання, висновок;plausibel|—|правдоподібний;stringent|—|послідовний;empirisch|—|емпіричний;fundiert|—|обґрунтований;nachvollziehbar|—|зрозумілий;widerlegen|—|спростовувати;untermauern|—|підкріплювати;erörtern|—|обговорювати;abwägen|—|зважувати;die Aussagekraft|—|переконливість`,
"Юридична й ділова мова":`die Rechtslage|-n|правова ситуація;der Sachverhalt|-e|обставини справи;die Klausel|-n|застереження;die Haftung|-en|відповідальність;die Verjährung|-en|позовна давність;der Verstoß|¨-e|порушення;die Auflage|-n|припис, вимога;die Vollmacht|-en|довіреність;die Zustimmung|-en|згода;der Vorbehalt|-e|застереження;rechtskräftig|—|чинний за законом;verbindlich|—|обов'язковий;zulässig|—|допустимий;untersagen|—|забороняти;beanstanden|—|оскаржувати;die Kündigungsfrist|-en|строк розірвання;die Gewährleistung|-en|гарантія;der Geltungsbereich|-e|сфера дії;die Auslegung|-en|тлумачення;der Nachtrag|¨-e|додаток до угоди`,
"Публіцистика й риторика":`die Rhetorik|—|риторика;die Polemik|-en|полеміка;die Pointe|-n|кульмінація думки;die Ironie|-n|іронія;der Zynismus|—|цинізм;die Anspielung|-en|натяк;die Übertreibung|-en|перебільшення;die Untertreibung|-en|применшення;der Vorwand|¨-e|привід, відмовка;die Rhetorikfigur|-en|риторична фігура;zuspitzen|—|загострювати;relativieren|—|релятивізувати;polarisieren|—|поляризувати;entlarven|—|викривати;beschönigen|—|прикрашати;suggerieren|—|навіювати;die Deutungshoheit|—|монополія на тлумачення;pointiert|—|влучний;polemisch|—|полемічний;subtil|—|витончений`,
"Відтінки емоцій":`die Wehmut|—|світла туга;die Sehnsucht|¨-e|туга за чимось;die Gelassenheit|—|незворушність;die Verbitterung|—|озлобленість;die Ehrfurcht|—|благоговіння;das Unbehagen|—|дискомфорт;die Zuversicht|—|упевненість у майбутньому;die Ernüchterung|-en|витвереження;die Rührung|—|зворушення;die Beklommenheit|—|тривожна стисненість;der Überdruss|—|пересит;die Reue|—|каяття;die Genugtuung|—|задоволення від справедливості;die Schadenfreude|—|зловтіха;die Fassungslosigkeit|—|приголомшеність;bestürzt|—|приголомшений;verhalten|—|стриманий;überschwänglich|—|надмірно захоплений;abgeklärt|—|врівноважений;wehmütig|—|тужливий`,
"Історія й пам'ять":`die Vergangenheitsbewältigung|—|переосмислення минулого;das Gedenken|—|вшанування пам'яті;die Erinnerungskultur|-en|культура пам'яті;der Zeitzeuge|-n|очевидець епохи;die Nachkriegszeit|-en|повоєнний час;die Wende|-n|злам, зміна епохи;die Wiedervereinigung|-en|возз'єднання;das Erbe|—|спадщина;die Aufarbeitung|-en|опрацювання минулого;die Verdrängung|-en|витіснення;der Wendepunkt|-e|переломний момент;die Epoche|-n|епоха;prägen|—|формувати;überliefern|—|передавати з покоління;verklären|—|ідеалізувати;die Kontinuität|-en|тяглість;der Bruch|¨-e|розрив;maßgeblich|—|визначальний;nachwirken|—|мати наслідки;die Zäsur|-en|цезура, злам`,
"Етика й мораль":`die Verantwortung|-en|відповідальність;das Gewissen|-|сумління;die Würde|—|гідність;die Integrität|—|доброчесність;das Dilemma|-s|дилема;die Zumutung|-en|неприйнятна вимога;die Willkür|—|свавілля;die Rücksichtslosigkeit|—|безцеремонність;die Aufrichtigkeit|—|щирість;die Heuchelei|-en|лицемірство;vertretbar|—|виправданий;fragwürdig|—|сумнівний;anmaßend|—|зухвалий;skrupellos|—|безпринципний;lauter|—|бездоганно чесний;sich anmaßen|—|привласнювати право;abwägen|—|зважувати за і проти;in Kauf nehmen|—|свідомо допускати;die Gesinnung|-en|переконання;der Grundsatz|¨-e|принцип`,
"Стійкі метафори":`den Ton angeben|—|задавати тон;ins Gewicht fallen|—|мати вагу;auf der Hand liegen|—|бути очевидним;aus dem Ruder laufen|—|виходити з-під контролю;den Rahmen sprengen|—|виходити за межі;Wellen schlagen|—|викликати резонанс;im Argen liegen|—|бути в занепаді;auf Eis legen|—|заморозити справу;zu Buche schlagen|—|відчутно позначатися;Schule machen|—|ставати прикладом;die Weichen stellen|—|задавати напрям;ins Stocken geraten|—|застопорюватися;im Keim ersticken|—|придушити в зародку;Öl ins Feuer gießen|—|підливати масла у вогонь;den Boden bereiten|—|готувати ґрунт;Hand in Hand gehen|—|іти пліч-о-пліч;aus dem Boden stampfen|—|створити з нічого;auf dem Prüfstand stehen|—|бути під перевіркою;den Nagel auf den Kopf treffen|—|влучити в яблучко;über Bord werfen|—|викидати за борт`,
"Розмовні ідіоми":`Bock haben|—|мати охоту;keinen Plan haben|—|не мати уявлення;auf den Keks gehen|—|діяти на нерви;die Nase voll haben|—|бути ситим по горло;jemanden abblitzen lassen|—|відшити когось;sich ins Zeug legen|—|викладатися;jemandem die Daumen drücken|—|тримати кулаки;auf dicke Hose machen|—|випендрюватися;ins Fettnäpfchen treten|—|сісти в калюжу;Tacheles reden|—|говорити прямо;jemanden auf dem Schirm haben|—|тримати на увазі;etwas auf die Reihe kriegen|—|дати раду чомусь;null Ahnung|—|нуль розуміння;kein Ding|—|дрібниці;das ist mir Wurst|—|мені байдуже;durch die Lappen gehen|—|вислизнути;auf Zack sein|—|бути кмітливим;abwarten und Tee trinken|—|почекати й побачити;jemandem einen Bären aufbinden|—|розповідати небилиці;die Kirche im Dorf lassen|—|не перебільшувати`,
"Словотвір і префікси":`zer-|—|руйнівний префікс;ver-|—|хибність або завершення;ent-|—|видалення чи початок;be-|—|робить дієслово перехідним;er-|—|досягнення результату;miss-|—|негативна оцінка;zerbrechen|—|розбивати вщент;verlernen|—|розучитися;entlassen|—|звільняти;bearbeiten|—|обробляти;erarbeiten|—|напрацьовувати;missverstehen|—|неправильно розуміти;-bar|—|можливість дії;-los|—|відсутність ознаки;-haft|—|подібність;-mäßig|—|відповідність;-sam|—|схильність;-wert|—|вартий чогось;unumgänglich|—|неминучий;unabdingbar|—|невід'ємний`,
"Дискурсивні маркери":`gleichwohl|—|проте;indes|—|тим часом, однак;mithin|—|отже;insofern|—|остільки;zumal|—|тим паче що;sofern|—|за умови що;ungeachtet|—|попри;geschweige denn|—|не кажучи вже про;vielmehr|—|радше, навпаки;letztlich|—|зрештою;keineswegs|—|аж ніяк;durchaus|—|цілком;ohnehin|—|і так, все одно;nichtsdestotrotz|—|попри все;im Zuge|—|у ході;hinsichtlich|—|стосовно;bezüglich|—|щодо;angesichts|—|з огляду на;dementsprechend|—|відповідно;folglich|—|отже`
};
