/* ---- B2 · додаткові 200 ---- */
VN.B2 = {
"Ринок праці":`die Arbeitslosigkeit|—|безробіття;der Fachkräftemangel|—|брак фахівців;die Qualifikation|-en|кваліфікація;die Belegschaft|-en|штат працівників;der Tarifvertrag|¨-e|тарифна угода;die Gewerkschaft|-en|профспілка;der Mindestlohn|¨-e|мінімальна зарплата;die Teilzeit|—|неповна зайнятість;die Vollzeit|—|повна зайнятість;die Selbstständigkeit|—|самозайнятість;der Arbeitgeber|-|роботодавець;der Arbeitnehmer|-|найманий працівник;die Einstellung|-en|прийняття на роботу;die Entlassung|-en|звільнення;die Vergütung|-en|винагорода;die Beförderung|-en|підвищення;die Anforderung|-en|вимога;die Zuständigkeit|-en|сфера відповідальності;flexibel|—|гнучкий;anspruchsvoll|—|вимогливий`,
"Освітня система":`die Grundschule|-n|початкова школа;das Gymnasium|Gymnasien|гімназія;die Ausbildung|-en|професійне навчання;das Studium|Studien|навчання у виші;der Studiengang|¨-e|спеціальність;die Fakultät|-en|факультет;das Stipendium|Stipendien|стипендія;die Vorlesung|-en|лекція;das Seminar|-e|семінар;die Hausarbeit|-en|курсова робота;die Bachelorarbeit|-en|бакалаврська робота;die Zulassung|-en|допуск;die Bildungspolitik|—|освітня політика;die Chancengleichheit|—|рівність можливостей;der Lehrplan|¨-e|навчальний план;der Abschluss|¨-e|випуск, диплом;die Leistung|-en|результат;bestehen|—|скласти іспит;durchfallen|—|провалити іспит;die Weiterbildung|-en|післядипломна освіта`,
"Система охорони здоров'я":`das Gesundheitssystem|-e|система охорони здоров'я;die Krankenkasse|-n|лікарняна каса;der Beitrag|¨-e|внесок;die Vorsorge|-n|профілактика;die Diagnose|-n|діагноз;die Therapie|-n|терапія;der Eingriff|-e|втручання;die Pflege|—|догляд;der Pflegefall|¨-e|потреба в догляді;die Impfung|-en|щеплення;die Nebenwirkung|-en|побічний ефект;chronisch|—|хронічний;akut|—|гострий;die Sterblichkeit|—|смертність;die Lebenserwartung|-en|тривалість життя;die Epidemie|-n|епідемія;der Erreger|-|збудник;ambulant|—|амбулаторний;stationär|—|стаціонарний;die Zulassung|-en|схвалення препарату`,
"Цифровізація":`die Digitalisierung|—|цифровізація;der Datenschutz|—|захист даних;der Algorithmus|Algorithmen|алгоритм;die Künstliche Intelligenz|—|штучний інтелект;die Schnittstelle|-n|інтерфейс;der Datensatz|¨-e|набір даних;die Verschlüsselung|-en|шифрування;die Sicherheitslücke|-n|вразливість;der Zugriff|-e|доступ;die Anwendung|-en|застосування;automatisieren|—|автоматизувати;vernetzen|—|з'єднувати мережею;speichern|—|зберігати;auswerten|—|аналізувати;der Fortschritt|-e|прогрес;die Überwachung|-en|стеження;der Missbrauch|¨-e|зловживання;anfällig|—|вразливий;zuverlässig|—|надійний;die Transparenz|—|прозорість`,
"Урбаністика й житло":`der Wohnraum|¨-e|житлова площа;die Mietpreisbremse|-n|обмеження орендних цін;die Verdichtung|-en|ущільнення забудови;die Zersiedelung|—|розповзання забудови;der Neubau|-ten|новобудова;die Sanierung|-en|санація будівлі;das Grundstück|-e|земельна ділянка;der Bebauungsplan|¨-e|план забудови;die Gentrifizierung|—|джентрифікація;die Wohnungsnot|—|житлова криза;der Leerstand|—|порожні приміщення;die Nahversorgung|—|місцеве постачання;die Anbindung|-en|транспортна доступність;der Ballungsraum|¨-e|агломерація;die Lebensqualität|—|якість життя;das Viertel|-|квартал;bezahlbar|—|доступний за ціною;begrenzt|—|обмежений;die Genossenschaft|-en|кооператив;die Zuwanderung|-en|приплив населення`,
"Дані й статистика":`die Umfrage|-n|опитування;die Stichprobe|-n|вибірка;der Durchschnitt|-e|середнє значення;der Anteil|-e|частка;die Zunahme|-n|зростання;die Abnahme|-n|зменшення;der Rückgang|¨-e|спад;die Entwicklung|-en|розвиток;die Tendenz|-en|тенденція;der Zusammenhang|¨-e|взаємозв'язок;die Verteilung|-en|розподіл;die Quote|-n|квота;schätzen|—|оцінювати;erheben|—|збирати дані;darstellen|—|представляти;die Grafik|-en|графік;deutlich|—|виразний;geringfügig|—|незначний;beträchtlich|—|значний;die Schwankung|-en|коливання`,
"Конфлікт і переговори":`der Streit|-e|суперечка;die Auseinandersetzung|-en|конфронтація;die Verhandlung|-en|переговори;das Zugeständnis|-se|поступка;die Einigung|-en|домовленість;der Vermittler|-|посередник;die Spannung|-en|напруга;eskalieren|—|загострювати;schlichten|—|залагоджувати;nachgeben|—|поступатися;bestehen auf|—|наполягати на;drohen|—|погрожувати;beschuldigen|—|звинувачувати;rechtfertigen|—|виправдовувати;die Bedingung|-en|умова;der Vorwurf|¨-e|докір;die Absprache|-n|усна домовленість;beilegen|—|улагоджувати;strittig|—|спірний;die Lösung|-en|рішення`,
"Причина й наслідок":`die Ursache|-n|причина;die Auswirkung|-en|вплив;der Anlass|¨-e|привід;die Konsequenz|-en|наслідок;bewirken|—|спричиняти;verursachen|—|викликати;beeinflussen|—|впливати;zurückführen auf|—|зводити до;hervorrufen|—|викликати;bedingen|—|зумовлювати;resultieren|—|випливати;auslösen|—|запускати;begünstigen|—|сприяти;hemmen|—|гальмувати;verstärken|—|посилювати;abschwächen|—|послаблювати;der Faktor|-en|чинник;maßgeblich|—|визначальний;unvermeidlich|—|неминучий;die Wechselwirkung|-en|взаємодія`,
"Номіналізації":`die Entstehung|-en|виникнення;die Umsetzung|-en|реалізація;die Durchführung|-en|проведення;die Erhöhung|-en|підвищення;die Senkung|-en|зниження;die Verbesserung|-en|покращення;die Verschlechterung|-en|погіршення;die Einführung|-en|запровадження;die Abschaffung|-en|скасування;die Verpflichtung|-en|зобов'язання;die Berücksichtigung|—|врахування;die Wahrnehmung|-en|сприйняття;die Gleichheit|—|рівність;die Sicherheit|-en|надійність;die Notwendigkeit|-en|необхідність;die Zuverlässigkeit|—|надійність;die Verantwortlichkeit|-en|відповідальність;die Bereitschaft|-en|готовність;die Fähigkeit|-en|здатність;die Möglichkeit|-en|можливість`,
"Функціональні дієслова":`in Betracht ziehen|—|брати до уваги;zur Verfügung stehen|—|бути в розпорядженні;in Frage stellen|—|ставити під сумнів;Rücksicht nehmen|—|зважати;eine Rolle spielen|—|відігравати роль;zum Ausdruck bringen|—|виражати;in Kraft treten|—|набирати чинності;Anspruch erheben|—|висувати претензію;Bezug nehmen|—|посилатися;in Erwägung ziehen|—|розглядати;Abstand nehmen|—|утримуватися;zur Sprache bringen|—|порушувати тему;in Kauf nehmen|—|миритися з;Stellung nehmen|—|висловлювати позицію;zur Folge haben|—|мати наслідком;unter Druck setzen|—|тиснути;in Anspruch nehmen|—|користуватися;Wert legen auf|—|надавати значення;die Entscheidung treffen|—|ухвалювати рішення;Kritik üben|—|критикувати`
};
